// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: rin/problem/v1/problem.proto

package problemv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProblemService_CreateProblemDraft_FullMethodName     = "/rin.problem.v1.ProblemService/CreateProblemDraft"
	ProblemService_ValidateProblemImport_FullMethodName  = "/rin.problem.v1.ProblemService/ValidateProblemImport"
	ProblemService_TeacherQuickUpload_FullMethodName     = "/rin.problem.v1.ProblemService/TeacherQuickUpload"
	ProblemService_StudentDraftSubmission_FullMethodName = "/rin.problem.v1.ProblemService/StudentDraftSubmission"
	ProblemService_CreatePresignedUpload_FullMethodName  = "/rin.problem.v1.ProblemService/CreatePresignedUpload"
	ProblemService_PublishProblem_FullMethodName         = "/rin.problem.v1.ProblemService/PublishProblem"
	ProblemService_GetProblem_FullMethodName             = "/rin.problem.v1.ProblemService/GetProblem"
	ProblemService_ListProblems_FullMethodName           = "/rin.problem.v1.ProblemService/ListProblems"
)

// ProblemServiceClient is the client API for ProblemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProblemServiceClient interface {
	CreateProblemDraft(ctx context.Context, in *CreateProblemDraftRequest, opts ...grpc.CallOption) (*ProblemDraft, error)
	ValidateProblemImport(ctx context.Context, in *ValidateProblemImportRequest, opts ...grpc.CallOption) (*ImportWizard, error)
	TeacherQuickUpload(ctx context.Context, in *TeacherQuickUploadRequest, opts ...grpc.CallOption) (*ProblemDraft, error)
	StudentDraftSubmission(ctx context.Context, in *StudentDraftSubmissionRequest, opts ...grpc.CallOption) (*ProblemDraft, error)
	CreatePresignedUpload(ctx context.Context, in *CreatePresignedUploadRequest, opts ...grpc.CallOption) (*CreatePresignedUploadResponse, error)
	PublishProblem(ctx context.Context, in *PublishProblemRequest, opts ...grpc.CallOption) (*Problem, error)
	GetProblem(ctx context.Context, in *GetProblemRequest, opts ...grpc.CallOption) (*Problem, error)
	ListProblems(ctx context.Context, in *ListProblemsRequest, opts ...grpc.CallOption) (*ListProblemsResponse, error)
}

type problemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProblemServiceClient(cc grpc.ClientConnInterface) ProblemServiceClient {
	return &problemServiceClient{cc}
}

func (c *problemServiceClient) CreateProblemDraft(ctx context.Context, in *CreateProblemDraftRequest, opts ...grpc.CallOption) (*ProblemDraft, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProblemDraft)
	err := c.cc.Invoke(ctx, ProblemService_CreateProblemDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) ValidateProblemImport(ctx context.Context, in *ValidateProblemImportRequest, opts ...grpc.CallOption) (*ImportWizard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportWizard)
	err := c.cc.Invoke(ctx, ProblemService_ValidateProblemImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) TeacherQuickUpload(ctx context.Context, in *TeacherQuickUploadRequest, opts ...grpc.CallOption) (*ProblemDraft, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProblemDraft)
	err := c.cc.Invoke(ctx, ProblemService_TeacherQuickUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) StudentDraftSubmission(ctx context.Context, in *StudentDraftSubmissionRequest, opts ...grpc.CallOption) (*ProblemDraft, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProblemDraft)
	err := c.cc.Invoke(ctx, ProblemService_StudentDraftSubmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) CreatePresignedUpload(ctx context.Context, in *CreatePresignedUploadRequest, opts ...grpc.CallOption) (*CreatePresignedUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePresignedUploadResponse)
	err := c.cc.Invoke(ctx, ProblemService_CreatePresignedUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) PublishProblem(ctx context.Context, in *PublishProblemRequest, opts ...grpc.CallOption) (*Problem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Problem)
	err := c.cc.Invoke(ctx, ProblemService_PublishProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetProblem(ctx context.Context, in *GetProblemRequest, opts ...grpc.CallOption) (*Problem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Problem)
	err := c.cc.Invoke(ctx, ProblemService_GetProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) ListProblems(ctx context.Context, in *ListProblemsRequest, opts ...grpc.CallOption) (*ListProblemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProblemsResponse)
	err := c.cc.Invoke(ctx, ProblemService_ListProblems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProblemServiceServer is the server API for ProblemService service.
// All implementations must embed UnimplementedProblemServiceServer
// for forward compatibility.
type ProblemServiceServer interface {
	CreateProblemDraft(context.Context, *CreateProblemDraftRequest) (*ProblemDraft, error)
	ValidateProblemImport(context.Context, *ValidateProblemImportRequest) (*ImportWizard, error)
	TeacherQuickUpload(context.Context, *TeacherQuickUploadRequest) (*ProblemDraft, error)
	StudentDraftSubmission(context.Context, *StudentDraftSubmissionRequest) (*ProblemDraft, error)
	CreatePresignedUpload(context.Context, *CreatePresignedUploadRequest) (*CreatePresignedUploadResponse, error)
	PublishProblem(context.Context, *PublishProblemRequest) (*Problem, error)
	GetProblem(context.Context, *GetProblemRequest) (*Problem, error)
	ListProblems(context.Context, *ListProblemsRequest) (*ListProblemsResponse, error)
	mustEmbedUnimplementedProblemServiceServer()
}

// UnimplementedProblemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProblemServiceServer struct{}

func (UnimplementedProblemServiceServer) CreateProblemDraft(context.Context, *CreateProblemDraftRequest) (*ProblemDraft, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProblemDraft not implemented")
}
func (UnimplementedProblemServiceServer) ValidateProblemImport(context.Context, *ValidateProblemImportRequest) (*ImportWizard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateProblemImport not implemented")
}
func (UnimplementedProblemServiceServer) TeacherQuickUpload(context.Context, *TeacherQuickUploadRequest) (*ProblemDraft, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TeacherQuickUpload not implemented")
}
func (UnimplementedProblemServiceServer) StudentDraftSubmission(context.Context, *StudentDraftSubmissionRequest) (*ProblemDraft, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StudentDraftSubmission not implemented")
}
func (UnimplementedProblemServiceServer) CreatePresignedUpload(context.Context, *CreatePresignedUploadRequest) (*CreatePresignedUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePresignedUpload not implemented")
}
func (UnimplementedProblemServiceServer) PublishProblem(context.Context, *PublishProblemRequest) (*Problem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishProblem not implemented")
}
func (UnimplementedProblemServiceServer) GetProblem(context.Context, *GetProblemRequest) (*Problem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblem not implemented")
}
func (UnimplementedProblemServiceServer) ListProblems(context.Context, *ListProblemsRequest) (*ListProblemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProblems not implemented")
}
func (UnimplementedProblemServiceServer) mustEmbedUnimplementedProblemServiceServer() {}
func (UnimplementedProblemServiceServer) testEmbeddedByValue()                        {}

// UnsafeProblemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProblemServiceServer will
// result in compilation errors.
type UnsafeProblemServiceServer interface {
	mustEmbedUnimplementedProblemServiceServer()
}

func RegisterProblemServiceServer(s grpc.ServiceRegistrar, srv ProblemServiceServer) {
	// If the following call pancis, it indicates UnimplementedProblemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProblemService_ServiceDesc, srv)
}

func _ProblemService_CreateProblemDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProblemDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).CreateProblemDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_CreateProblemDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).CreateProblemDraft(ctx, req.(*CreateProblemDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_ValidateProblemImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateProblemImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).ValidateProblemImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_ValidateProblemImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).ValidateProblemImport(ctx, req.(*ValidateProblemImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_TeacherQuickUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeacherQuickUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).TeacherQuickUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_TeacherQuickUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).TeacherQuickUpload(ctx, req.(*TeacherQuickUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_StudentDraftSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentDraftSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).StudentDraftSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_StudentDraftSubmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).StudentDraftSubmission(ctx, req.(*StudentDraftSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_CreatePresignedUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePresignedUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).CreatePresignedUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_CreatePresignedUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).CreatePresignedUpload(ctx, req.(*CreatePresignedUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_PublishProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).PublishProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_PublishProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).PublishProblem(ctx, req.(*PublishProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_GetProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetProblem(ctx, req.(*GetProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_ListProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProblemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).ListProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_ListProblems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).ListProblems(ctx, req.(*ListProblemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProblemService_ServiceDesc is the grpc.ServiceDesc for ProblemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProblemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rin.problem.v1.ProblemService",
	HandlerType: (*ProblemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProblemDraft",
			Handler:    _ProblemService_CreateProblemDraft_Handler,
		},
		{
			MethodName: "ValidateProblemImport",
			Handler:    _ProblemService_ValidateProblemImport_Handler,
		},
		{
			MethodName: "TeacherQuickUpload",
			Handler:    _ProblemService_TeacherQuickUpload_Handler,
		},
		{
			MethodName: "StudentDraftSubmission",
			Handler:    _ProblemService_StudentDraftSubmission_Handler,
		},
		{
			MethodName: "CreatePresignedUpload",
			Handler:    _ProblemService_CreatePresignedUpload_Handler,
		},
		{
			MethodName: "PublishProblem",
			Handler:    _ProblemService_PublishProblem_Handler,
		},
		{
			MethodName: "GetProblem",
			Handler:    _ProblemService_GetProblem_Handler,
		},
		{
			MethodName: "ListProblems",
			Handler:    _ProblemService_ListProblems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rin/problem/v1/problem.proto",
}
