// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rin/problem/v1/problem.proto

package problemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProblemVisibility int32

const (
	ProblemVisibility_PROBLEM_VISIBILITY_UNSPECIFIED  ProblemVisibility = 0
	ProblemVisibility_PROBLEM_VISIBILITY_PRIVATE      ProblemVisibility = 1
	ProblemVisibility_PROBLEM_VISIBILITY_REVIEW       ProblemVisibility = 2
	ProblemVisibility_PROBLEM_VISIBILITY_PUBLIC       ProblemVisibility = 3
	ProblemVisibility_PROBLEM_VISIBILITY_CONTEST_ONLY ProblemVisibility = 4
)

// Enum value maps for ProblemVisibility.
var (
	ProblemVisibility_name = map[int32]string{
		0: "PROBLEM_VISIBILITY_UNSPECIFIED",
		1: "PROBLEM_VISIBILITY_PRIVATE",
		2: "PROBLEM_VISIBILITY_REVIEW",
		3: "PROBLEM_VISIBILITY_PUBLIC",
		4: "PROBLEM_VISIBILITY_CONTEST_ONLY",
	}
	ProblemVisibility_value = map[string]int32{
		"PROBLEM_VISIBILITY_UNSPECIFIED":  0,
		"PROBLEM_VISIBILITY_PRIVATE":      1,
		"PROBLEM_VISIBILITY_REVIEW":       2,
		"PROBLEM_VISIBILITY_PUBLIC":       3,
		"PROBLEM_VISIBILITY_CONTEST_ONLY": 4,
	}
)

func (x ProblemVisibility) Enum() *ProblemVisibility {
	p := new(ProblemVisibility)
	*p = x
	return p
}

func (x ProblemVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProblemVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_rin_problem_v1_problem_proto_enumTypes[0].Descriptor()
}

func (ProblemVisibility) Type() protoreflect.EnumType {
	return &file_rin_problem_v1_problem_proto_enumTypes[0]
}

func (x ProblemVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProblemVisibility.Descriptor instead.
func (ProblemVisibility) EnumDescriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{0}
}

type ProblemType int32

const (
	ProblemType_PROBLEM_TYPE_UNSPECIFIED   ProblemType = 0
	ProblemType_PROBLEM_TYPE_TRADITIONAL   ProblemType = 1
	ProblemType_PROBLEM_TYPE_SPECIAL_JUDGE ProblemType = 2
	ProblemType_PROBLEM_TYPE_INTERACTIVE   ProblemType = 3
	ProblemType_PROBLEM_TYPE_SUBMIT_ANSWER ProblemType = 4
	ProblemType_PROBLEM_TYPE_OUTPUT_ONLY   ProblemType = 5
	ProblemType_PROBLEM_TYPE_COMMUNICATION ProblemType = 6
)

// Enum value maps for ProblemType.
var (
	ProblemType_name = map[int32]string{
		0: "PROBLEM_TYPE_UNSPECIFIED",
		1: "PROBLEM_TYPE_TRADITIONAL",
		2: "PROBLEM_TYPE_SPECIAL_JUDGE",
		3: "PROBLEM_TYPE_INTERACTIVE",
		4: "PROBLEM_TYPE_SUBMIT_ANSWER",
		5: "PROBLEM_TYPE_OUTPUT_ONLY",
		6: "PROBLEM_TYPE_COMMUNICATION",
	}
	ProblemType_value = map[string]int32{
		"PROBLEM_TYPE_UNSPECIFIED":   0,
		"PROBLEM_TYPE_TRADITIONAL":   1,
		"PROBLEM_TYPE_SPECIAL_JUDGE": 2,
		"PROBLEM_TYPE_INTERACTIVE":   3,
		"PROBLEM_TYPE_SUBMIT_ANSWER": 4,
		"PROBLEM_TYPE_OUTPUT_ONLY":   5,
		"PROBLEM_TYPE_COMMUNICATION": 6,
	}
)

func (x ProblemType) Enum() *ProblemType {
	p := new(ProblemType)
	*p = x
	return p
}

func (x ProblemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProblemType) Descriptor() protoreflect.EnumDescriptor {
	return file_rin_problem_v1_problem_proto_enumTypes[1].Descriptor()
}

func (ProblemType) Type() protoreflect.EnumType {
	return &file_rin_problem_v1_problem_proto_enumTypes[1]
}

func (x ProblemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProblemType.Descriptor instead.
func (ProblemType) EnumDescriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{1}
}

type Problem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     string                 `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Type          ProblemType            `protobuf:"varint,4,opt,name=type,proto3,enum=rin.problem.v1.ProblemType" json:"type,omitempty"`
	Visibility    ProblemVisibility      `protobuf:"varint,5,opt,name=visibility,proto3,enum=rin.problem.v1.ProblemVisibility" json:"visibility,omitempty"`
	Difficulty    int32                  `protobuf:"varint,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Statements    []*LocalizedStatement  `protobuf:"bytes,8,rep,name=statements,proto3" json:"statements,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,9,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Version       int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{0}
}

func (x *Problem) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *Problem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Problem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Problem) GetType() ProblemType {
	if x != nil {
		return x.Type
	}
	return ProblemType_PROBLEM_TYPE_UNSPECIFIED
}

func (x *Problem) GetVisibility() ProblemVisibility {
	if x != nil {
		return x.Visibility
	}
	return ProblemVisibility_PROBLEM_VISIBILITY_UNSPECIFIED
}

func (x *Problem) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *Problem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Problem) GetStatements() []*LocalizedStatement {
	if x != nil {
		return x.Statements
	}
	return nil
}

func (x *Problem) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Problem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type LocalizedStatement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Markdown      string                 `protobuf:"bytes,3,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalizedStatement) Reset() {
	*x = LocalizedStatement{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalizedStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizedStatement) ProtoMessage() {}

func (x *LocalizedStatement) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizedStatement.ProtoReflect.Descriptor instead.
func (*LocalizedStatement) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{1}
}

func (x *LocalizedStatement) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *LocalizedStatement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LocalizedStatement) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type ProblemDraft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       string                 `protobuf:"bytes,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	ProblemId     string                 `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Visibility    ProblemVisibility      `protobuf:"varint,4,opt,name=visibility,proto3,enum=rin.problem.v1.ProblemVisibility" json:"visibility,omitempty"`
	ImportWizard  *ImportWizard          `protobuf:"bytes,5,opt,name=import_wizard,json=importWizard,proto3" json:"import_wizard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemDraft) Reset() {
	*x = ProblemDraft{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemDraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemDraft) ProtoMessage() {}

func (x *ProblemDraft) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemDraft.ProtoReflect.Descriptor instead.
func (*ProblemDraft) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{2}
}

func (x *ProblemDraft) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

func (x *ProblemDraft) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *ProblemDraft) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *ProblemDraft) GetVisibility() ProblemVisibility {
	if x != nil {
		return x.Visibility
	}
	return ProblemVisibility_PROBLEM_VISIBILITY_UNSPECIFIED
}

func (x *ProblemDraft) GetImportWizard() *ImportWizard {
	if x != nil {
		return x.ImportWizard
	}
	return nil
}

type CreateProblemDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          ProblemType            `protobuf:"varint,3,opt,name=type,proto3,enum=rin.problem.v1.ProblemType" json:"type,omitempty"`
	Statements    []*LocalizedStatement  `protobuf:"bytes,4,rep,name=statements,proto3" json:"statements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProblemDraftRequest) Reset() {
	*x = CreateProblemDraftRequest{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProblemDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProblemDraftRequest) ProtoMessage() {}

func (x *CreateProblemDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProblemDraftRequest.ProtoReflect.Descriptor instead.
func (*CreateProblemDraftRequest) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProblemDraftRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CreateProblemDraftRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProblemDraftRequest) GetType() ProblemType {
	if x != nil {
		return x.Type
	}
	return ProblemType_PROBLEM_TYPE_UNSPECIFIED
}

func (x *CreateProblemDraftRequest) GetStatements() []*LocalizedStatement {
	if x != nil {
		return x.Statements
	}
	return nil
}

type ValidateProblemImportRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorId         string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	UploadObjectKey string                 `protobuf:"bytes,2,opt,name=upload_object_key,json=uploadObjectKey,proto3" json:"upload_object_key,omitempty"`
	SourceFilename  string                 `protobuf:"bytes,3,opt,name=source_filename,json=sourceFilename,proto3" json:"source_filename,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateProblemImportRequest) Reset() {
	*x = ValidateProblemImportRequest{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProblemImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProblemImportRequest) ProtoMessage() {}

func (x *ValidateProblemImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProblemImportRequest.ProtoReflect.Descriptor instead.
func (*ValidateProblemImportRequest) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateProblemImportRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ValidateProblemImportRequest) GetUploadObjectKey() string {
	if x != nil {
		return x.UploadObjectKey
	}
	return ""
}

func (x *ValidateProblemImportRequest) GetSourceFilename() string {
	if x != nil {
		return x.SourceFilename
	}
	return ""
}

type TeacherQuickUploadRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TeacherId          string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	ClassId            string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	UploadObjectKey    string                 `protobuf:"bytes,3,opt,name=upload_object_key,json=uploadObjectKey,proto3" json:"upload_object_key,omitempty"`
	PublishImmediately bool                   `protobuf:"varint,4,opt,name=publish_immediately,json=publishImmediately,proto3" json:"publish_immediately,omitempty"`
	RequestAdminReview bool                   `protobuf:"varint,5,opt,name=request_admin_review,json=requestAdminReview,proto3" json:"request_admin_review,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TeacherQuickUploadRequest) Reset() {
	*x = TeacherQuickUploadRequest{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherQuickUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherQuickUploadRequest) ProtoMessage() {}

func (x *TeacherQuickUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherQuickUploadRequest.ProtoReflect.Descriptor instead.
func (*TeacherQuickUploadRequest) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{5}
}

func (x *TeacherQuickUploadRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *TeacherQuickUploadRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *TeacherQuickUploadRequest) GetUploadObjectKey() string {
	if x != nil {
		return x.UploadObjectKey
	}
	return ""
}

func (x *TeacherQuickUploadRequest) GetPublishImmediately() bool {
	if x != nil {
		return x.PublishImmediately
	}
	return false
}

func (x *TeacherQuickUploadRequest) GetRequestAdminReview() bool {
	if x != nil {
		return x.RequestAdminReview
	}
	return false
}

type StudentDraftSubmissionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudentId       string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	ClassId         string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	UploadObjectKey string                 `protobuf:"bytes,3,opt,name=upload_object_key,json=uploadObjectKey,proto3" json:"upload_object_key,omitempty"`
	NoteToReviewer  string                 `protobuf:"bytes,4,opt,name=note_to_reviewer,json=noteToReviewer,proto3" json:"note_to_reviewer,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StudentDraftSubmissionRequest) Reset() {
	*x = StudentDraftSubmissionRequest{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentDraftSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentDraftSubmissionRequest) ProtoMessage() {}

func (x *StudentDraftSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentDraftSubmissionRequest.ProtoReflect.Descriptor instead.
func (*StudentDraftSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{6}
}

func (x *StudentDraftSubmissionRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentDraftSubmissionRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *StudentDraftSubmissionRequest) GetUploadObjectKey() string {
	if x != nil {
		return x.UploadObjectKey
	}
	return ""
}

func (x *StudentDraftSubmissionRequest) GetNoteToReviewer() string {
	if x != nil {
		return x.NoteToReviewer
	}
	return ""
}

type ImportWizard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImportId      string                 `protobuf:"bytes,1,opt,name=import_id,json=importId,proto3" json:"import_id,omitempty"`
	DetectedTitle string                 `protobuf:"bytes,2,opt,name=detected_title,json=detectedTitle,proto3" json:"detected_title,omitempty"`
	DetectedType  ProblemType            `protobuf:"varint,3,opt,name=detected_type,json=detectedType,proto3,enum=rin.problem.v1.ProblemType" json:"detected_type,omitempty"`
	Statements    []*LocalizedStatement  `protobuf:"bytes,4,rep,name=statements,proto3" json:"statements,omitempty"`
	Samples       []*SampleCase          `protobuf:"bytes,5,rep,name=samples,proto3" json:"samples,omitempty"`
	Validations   []*ImportValidation    `protobuf:"bytes,6,rep,name=validations,proto3" json:"validations,omitempty"`
	NextActions   []string               `protobuf:"bytes,7,rep,name=next_actions,json=nextActions,proto3" json:"next_actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportWizard) Reset() {
	*x = ImportWizard{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportWizard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportWizard) ProtoMessage() {}

func (x *ImportWizard) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportWizard.ProtoReflect.Descriptor instead.
func (*ImportWizard) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{7}
}

func (x *ImportWizard) GetImportId() string {
	if x != nil {
		return x.ImportId
	}
	return ""
}

func (x *ImportWizard) GetDetectedTitle() string {
	if x != nil {
		return x.DetectedTitle
	}
	return ""
}

func (x *ImportWizard) GetDetectedType() ProblemType {
	if x != nil {
		return x.DetectedType
	}
	return ProblemType_PROBLEM_TYPE_UNSPECIFIED
}

func (x *ImportWizard) GetStatements() []*LocalizedStatement {
	if x != nil {
		return x.Statements
	}
	return nil
}

func (x *ImportWizard) GetSamples() []*SampleCase {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *ImportWizard) GetValidations() []*ImportValidation {
	if x != nil {
		return x.Validations
	}
	return nil
}

func (x *ImportWizard) GetNextActions() []string {
	if x != nil {
		return x.NextActions
	}
	return nil
}

type SampleCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleCase) Reset() {
	*x = SampleCase{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleCase) ProtoMessage() {}

func (x *SampleCase) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleCase.ProtoReflect.Descriptor instead.
func (*SampleCase) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{8}
}

func (x *SampleCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SampleCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *SampleCase) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ImportValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportValidation) Reset() {
	*x = ImportValidation{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportValidation) ProtoMessage() {}

func (x *ImportValidation) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportValidation.ProtoReflect.Descriptor instead.
func (*ImportValidation) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{9}
}

func (x *ImportValidation) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ImportValidation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ImportValidation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ImportValidation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreatePresignedUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	PartCount     int32                  `protobuf:"varint,5,opt,name=part_count,json=partCount,proto3" json:"part_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePresignedUploadRequest) Reset() {
	*x = CreatePresignedUploadRequest{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePresignedUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePresignedUploadRequest) ProtoMessage() {}

func (x *CreatePresignedUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePresignedUploadRequest.ProtoReflect.Descriptor instead.
func (*CreatePresignedUploadRequest) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePresignedUploadRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CreatePresignedUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreatePresignedUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreatePresignedUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreatePresignedUploadRequest) GetPartCount() int32 {
	if x != nil {
		return x.PartCount
	}
	return 0
}

type CreatePresignedUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Parts         []*PresignedUploadPart `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePresignedUploadResponse) Reset() {
	*x = CreatePresignedUploadResponse{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePresignedUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePresignedUploadResponse) ProtoMessage() {}

func (x *CreatePresignedUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePresignedUploadResponse.ProtoReflect.Descriptor instead.
func (*CreatePresignedUploadResponse) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePresignedUploadResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *CreatePresignedUploadResponse) GetParts() []*PresignedUploadPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *CreatePresignedUploadResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type PresignedUploadPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignedUploadPart) Reset() {
	*x = PresignedUploadPart{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignedUploadPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignedUploadPart) ProtoMessage() {}

func (x *PresignedUploadPart) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignedUploadPart.ProtoReflect.Descriptor instead.
func (*PresignedUploadPart) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{12}
}

func (x *PresignedUploadPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *PresignedUploadPart) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *PresignedUploadPart) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type PublishProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	DraftId       string                 `protobuf:"bytes,2,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishProblemRequest) Reset() {
	*x = PublishProblemRequest{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishProblemRequest) ProtoMessage() {}

func (x *PublishProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishProblemRequest.ProtoReflect.Descriptor instead.
func (*PublishProblemRequest) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{13}
}

func (x *PublishProblemRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *PublishProblemRequest) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

type GetProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     string                 `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemRequest) Reset() {
	*x = GetProblemRequest{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemRequest) ProtoMessage() {}

func (x *GetProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemRequest.ProtoReflect.Descriptor instead.
func (*GetProblemRequest) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{14}
}

func (x *GetProblemRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *GetProblemRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type ListProblemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProblemsRequest) Reset() {
	*x = ListProblemsRequest{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProblemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProblemsRequest) ProtoMessage() {}

func (x *ListProblemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProblemsRequest.ProtoReflect.Descriptor instead.
func (*ListProblemsRequest) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{15}
}

func (x *ListProblemsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListProblemsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProblemsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListProblemsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListProblemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problems      []*Problem             `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProblemsResponse) Reset() {
	*x = ListProblemsResponse{}
	mi := &file_rin_problem_v1_problem_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProblemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProblemsResponse) ProtoMessage() {}

func (x *ListProblemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rin_problem_v1_problem_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProblemsResponse.ProtoReflect.Descriptor instead.
func (*ListProblemsResponse) Descriptor() ([]byte, []int) {
	return file_rin_problem_v1_problem_proto_rawDescGZIP(), []int{16}
}

func (x *ListProblemsResponse) GetProblems() []*Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

func (x *ListProblemsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_rin_problem_v1_problem_proto protoreflect.FileDescriptor

const file_rin_problem_v1_problem_proto_rawDesc = "" +
	"\n" +
	"\x1crin/problem/v1/problem.proto\x12\x0erin.problem.v1\"\xfc\x02\n" +
	"\aProblem\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\tR\tproblemId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12/\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.rin.problem.v1.ProblemTypeR\x04type\x12A\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2!.rin.problem.v1.ProblemVisibilityR\n" +
	"visibility\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\x05R\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12B\n" +
	"\n" +
	"statements\x18\b \x03(\v2\".rin.problem.v1.LocalizedStatementR\n" +
	"statements\x12\"\n" +
	"\rowner_user_id\x18\t \x01(\tR\vownerUserId\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\"^\n" +
	"\x12LocalizedStatement\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bmarkdown\x18\x03 \x01(\tR\bmarkdown\"\xf2\x01\n" +
	"\fProblemDraft\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\tR\adraftId\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\tR\tproblemId\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12A\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2!.rin.problem.v1.ProblemVisibilityR\n" +
	"visibility\x12A\n" +
	"\rimport_wizard\x18\x05 \x01(\v2\x1c.rin.problem.v1.ImportWizardR\fimportWizard\"\xc1\x01\n" +
	"\x19CreateProblemDraftRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.rin.problem.v1.ProblemTypeR\x04type\x12B\n" +
	"\n" +
	"statements\x18\x04 \x03(\v2\".rin.problem.v1.LocalizedStatementR\n" +
	"statements\"\x8e\x01\n" +
	"\x1cValidateProblemImportRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12*\n" +
	"\x11upload_object_key\x18\x02 \x01(\tR\x0fuploadObjectKey\x12'\n" +
	"\x0fsource_filename\x18\x03 \x01(\tR\x0esourceFilename\"\xe4\x01\n" +
	"\x19TeacherQuickUploadRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\x12*\n" +
	"\x11upload_object_key\x18\x03 \x01(\tR\x0fuploadObjectKey\x12/\n" +
	"\x13publish_immediately\x18\x04 \x01(\bR\x12publishImmediately\x120\n" +
	"\x14request_admin_review\x18\x05 \x01(\bR\x12requestAdminReview\"\xaf\x01\n" +
	"\x1dStudentDraftSubmissionRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\x12*\n" +
	"\x11upload_object_key\x18\x03 \x01(\tR\x0fuploadObjectKey\x12(\n" +
	"\x10note_to_reviewer\x18\x04 \x01(\tR\x0enoteToReviewer\"\xf5\x02\n" +
	"\fImportWizard\x12\x1b\n" +
	"\timport_id\x18\x01 \x01(\tR\bimportId\x12%\n" +
	"\x0edetected_title\x18\x02 \x01(\tR\rdetectedTitle\x12@\n" +
	"\rdetected_type\x18\x03 \x01(\x0e2\x1b.rin.problem.v1.ProblemTypeR\fdetectedType\x12B\n" +
	"\n" +
	"statements\x18\x04 \x03(\v2\".rin.problem.v1.LocalizedStatementR\n" +
	"statements\x124\n" +
	"\asamples\x18\x05 \x03(\v2\x1a.rin.problem.v1.SampleCaseR\asamples\x12B\n" +
	"\vvalidations\x18\x06 \x03(\v2 .rin.problem.v1.ImportValidationR\vvalidations\x12!\n" +
	"\fnext_actions\x18\a \x03(\tR\vnextActions\"N\n" +
	"\n" +
	"SampleCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"p\n" +
	"\x10ImportValidation\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\xb6\x01\n" +
	"\x1cCreatePresignedUploadRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"part_count\x18\x05 \x01(\x05R\tpartCount\"\xa1\x01\n" +
	"\x1dCreatePresignedUploadResponse\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x129\n" +
	"\x05parts\x18\x02 \x03(\v2#.rin.problem.v1.PresignedUploadPartR\x05parts\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\"\xdd\x01\n" +
	"\x13PresignedUploadPart\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12J\n" +
	"\aheaders\x18\x03 \x03(\v20.rin.problem.v1.PresignedUploadPart.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x15PublishProblemRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x19\n" +
	"\bdraft_id\x18\x02 \x01(\tR\adraftId\"J\n" +
	"\x11GetProblemRequest\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\tR\tproblemId\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"v\n" +
	"\x13ListProblemsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"l\n" +
	"\x14ListProblemsResponse\x123\n" +
	"\bproblems\x18\x01 \x03(\v2\x17.rin.problem.v1.ProblemR\bproblems\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor*\xba\x01\n" +
	"\x11ProblemVisibility\x12\"\n" +
	"\x1ePROBLEM_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPROBLEM_VISIBILITY_PRIVATE\x10\x01\x12\x1d\n" +
	"\x19PROBLEM_VISIBILITY_REVIEW\x10\x02\x12\x1d\n" +
	"\x19PROBLEM_VISIBILITY_PUBLIC\x10\x03\x12#\n" +
	"\x1fPROBLEM_VISIBILITY_CONTEST_ONLY\x10\x04*\xe5\x01\n" +
	"\vProblemType\x12\x1c\n" +
	"\x18PROBLEM_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PROBLEM_TYPE_TRADITIONAL\x10\x01\x12\x1e\n" +
	"\x1aPROBLEM_TYPE_SPECIAL_JUDGE\x10\x02\x12\x1c\n" +
	"\x18PROBLEM_TYPE_INTERACTIVE\x10\x03\x12\x1e\n" +
	"\x1aPROBLEM_TYPE_SUBMIT_ANSWER\x10\x04\x12\x1c\n" +
	"\x18PROBLEM_TYPE_OUTPUT_ONLY\x10\x05\x12\x1e\n" +
	"\x1aPROBLEM_TYPE_COMMUNICATION\x10\x062\x87\x06\n" +
	"\x0eProblemService\x12]\n" +
	"\x12CreateProblemDraft\x12).rin.problem.v1.CreateProblemDraftRequest\x1a\x1c.rin.problem.v1.ProblemDraft\x12c\n" +
	"\x15ValidateProblemImport\x12,.rin.problem.v1.ValidateProblemImportRequest\x1a\x1c.rin.problem.v1.ImportWizard\x12]\n" +
	"\x12TeacherQuickUpload\x12).rin.problem.v1.TeacherQuickUploadRequest\x1a\x1c.rin.problem.v1.ProblemDraft\x12e\n" +
	"\x16StudentDraftSubmission\x12-.rin.problem.v1.StudentDraftSubmissionRequest\x1a\x1c.rin.problem.v1.ProblemDraft\x12t\n" +
	"\x15CreatePresignedUpload\x12,.rin.problem.v1.CreatePresignedUploadRequest\x1a-.rin.problem.v1.CreatePresignedUploadResponse\x12P\n" +
	"\x0ePublishProblem\x12%.rin.problem.v1.PublishProblemRequest\x1a\x17.rin.problem.v1.Problem\x12H\n" +
	"\n" +
	"GetProblem\x12!.rin.problem.v1.GetProblemRequest\x1a\x17.rin.problem.v1.Problem\x12Y\n" +
	"\fListProblems\x12#.rin.problem.v1.ListProblemsRequest\x1a$.rin.problem.v1.ListProblemsResponseBCZAgithub.com/rin-oj/rin-oj/packages/sdk-go/rin/problem/v1;problemv1b\x06proto3"

var (
	file_rin_problem_v1_problem_proto_rawDescOnce sync.Once
	file_rin_problem_v1_problem_proto_rawDescData []byte
)

func file_rin_problem_v1_problem_proto_rawDescGZIP() []byte {
	file_rin_problem_v1_problem_proto_rawDescOnce.Do(func() {
		file_rin_problem_v1_problem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rin_problem_v1_problem_proto_rawDesc), len(file_rin_problem_v1_problem_proto_rawDesc)))
	})
	return file_rin_problem_v1_problem_proto_rawDescData
}

var file_rin_problem_v1_problem_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rin_problem_v1_problem_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_rin_problem_v1_problem_proto_goTypes = []any{
	(ProblemVisibility)(0),                // 0: rin.problem.v1.ProblemVisibility
	(ProblemType)(0),                      // 1: rin.problem.v1.ProblemType
	(*Problem)(nil),                       // 2: rin.problem.v1.Problem
	(*LocalizedStatement)(nil),            // 3: rin.problem.v1.LocalizedStatement
	(*ProblemDraft)(nil),                  // 4: rin.problem.v1.ProblemDraft
	(*CreateProblemDraftRequest)(nil),     // 5: rin.problem.v1.CreateProblemDraftRequest
	(*ValidateProblemImportRequest)(nil),  // 6: rin.problem.v1.ValidateProblemImportRequest
	(*TeacherQuickUploadRequest)(nil),     // 7: rin.problem.v1.TeacherQuickUploadRequest
	(*StudentDraftSubmissionRequest)(nil), // 8: rin.problem.v1.StudentDraftSubmissionRequest
	(*ImportWizard)(nil),                  // 9: rin.problem.v1.ImportWizard
	(*SampleCase)(nil),                    // 10: rin.problem.v1.SampleCase
	(*ImportValidation)(nil),              // 11: rin.problem.v1.ImportValidation
	(*CreatePresignedUploadRequest)(nil),  // 12: rin.problem.v1.CreatePresignedUploadRequest
	(*CreatePresignedUploadResponse)(nil), // 13: rin.problem.v1.CreatePresignedUploadResponse
	(*PresignedUploadPart)(nil),           // 14: rin.problem.v1.PresignedUploadPart
	(*PublishProblemRequest)(nil),         // 15: rin.problem.v1.PublishProblemRequest
	(*GetProblemRequest)(nil),             // 16: rin.problem.v1.GetProblemRequest
	(*ListProblemsRequest)(nil),           // 17: rin.problem.v1.ListProblemsRequest
	(*ListProblemsResponse)(nil),          // 18: rin.problem.v1.ListProblemsResponse
	nil,                                   // 19: rin.problem.v1.PresignedUploadPart.HeadersEntry
}
var file_rin_problem_v1_problem_proto_depIdxs = []int32{
	1,  // 0: rin.problem.v1.Problem.type:type_name -> rin.problem.v1.ProblemType
	0,  // 1: rin.problem.v1.Problem.visibility:type_name -> rin.problem.v1.ProblemVisibility
	3,  // 2: rin.problem.v1.Problem.statements:type_name -> rin.problem.v1.LocalizedStatement
	0,  // 3: rin.problem.v1.ProblemDraft.visibility:type_name -> rin.problem.v1.ProblemVisibility
	9,  // 4: rin.problem.v1.ProblemDraft.import_wizard:type_name -> rin.problem.v1.ImportWizard
	1,  // 5: rin.problem.v1.CreateProblemDraftRequest.type:type_name -> rin.problem.v1.ProblemType
	3,  // 6: rin.problem.v1.CreateProblemDraftRequest.statements:type_name -> rin.problem.v1.LocalizedStatement
	1,  // 7: rin.problem.v1.ImportWizard.detected_type:type_name -> rin.problem.v1.ProblemType
	3,  // 8: rin.problem.v1.ImportWizard.statements:type_name -> rin.problem.v1.LocalizedStatement
	10, // 9: rin.problem.v1.ImportWizard.samples:type_name -> rin.problem.v1.SampleCase
	11, // 10: rin.problem.v1.ImportWizard.validations:type_name -> rin.problem.v1.ImportValidation
	14, // 11: rin.problem.v1.CreatePresignedUploadResponse.parts:type_name -> rin.problem.v1.PresignedUploadPart
	19, // 12: rin.problem.v1.PresignedUploadPart.headers:type_name -> rin.problem.v1.PresignedUploadPart.HeadersEntry
	2,  // 13: rin.problem.v1.ListProblemsResponse.problems:type_name -> rin.problem.v1.Problem
	5,  // 14: rin.problem.v1.ProblemService.CreateProblemDraft:input_type -> rin.problem.v1.CreateProblemDraftRequest
	6,  // 15: rin.problem.v1.ProblemService.ValidateProblemImport:input_type -> rin.problem.v1.ValidateProblemImportRequest
	7,  // 16: rin.problem.v1.ProblemService.TeacherQuickUpload:input_type -> rin.problem.v1.TeacherQuickUploadRequest
	8,  // 17: rin.problem.v1.ProblemService.StudentDraftSubmission:input_type -> rin.problem.v1.StudentDraftSubmissionRequest
	12, // 18: rin.problem.v1.ProblemService.CreatePresignedUpload:input_type -> rin.problem.v1.CreatePresignedUploadRequest
	15, // 19: rin.problem.v1.ProblemService.PublishProblem:input_type -> rin.problem.v1.PublishProblemRequest
	16, // 20: rin.problem.v1.ProblemService.GetProblem:input_type -> rin.problem.v1.GetProblemRequest
	17, // 21: rin.problem.v1.ProblemService.ListProblems:input_type -> rin.problem.v1.ListProblemsRequest
	4,  // 22: rin.problem.v1.ProblemService.CreateProblemDraft:output_type -> rin.problem.v1.ProblemDraft
	9,  // 23: rin.problem.v1.ProblemService.ValidateProblemImport:output_type -> rin.problem.v1.ImportWizard
	4,  // 24: rin.problem.v1.ProblemService.TeacherQuickUpload:output_type -> rin.problem.v1.ProblemDraft
	4,  // 25: rin.problem.v1.ProblemService.StudentDraftSubmission:output_type -> rin.problem.v1.ProblemDraft
	13, // 26: rin.problem.v1.ProblemService.CreatePresignedUpload:output_type -> rin.problem.v1.CreatePresignedUploadResponse
	2,  // 27: rin.problem.v1.ProblemService.PublishProblem:output_type -> rin.problem.v1.Problem
	2,  // 28: rin.problem.v1.ProblemService.GetProblem:output_type -> rin.problem.v1.Problem
	18, // 29: rin.problem.v1.ProblemService.ListProblems:output_type -> rin.problem.v1.ListProblemsResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_rin_problem_v1_problem_proto_init() }
func file_rin_problem_v1_problem_proto_init() {
	if File_rin_problem_v1_problem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rin_problem_v1_problem_proto_rawDesc), len(file_rin_problem_v1_problem_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rin_problem_v1_problem_proto_goTypes,
		DependencyIndexes: file_rin_problem_v1_problem_proto_depIdxs,
		EnumInfos:         file_rin_problem_v1_problem_proto_enumTypes,
		MessageInfos:      file_rin_problem_v1_problem_proto_msgTypes,
	}.Build()
	File_rin_problem_v1_problem_proto = out.File
	file_rin_problem_v1_problem_proto_goTypes = nil
	file_rin_problem_v1_problem_proto_depIdxs = nil
}
