export const navItems = [
  { label: "Problems", labelKey: "nav.problems" as const, href: "/problems" },
  { label: "Contests", labelKey: "nav.contests" as const, href: "/contests" },
  { label: "Status", labelKey: "nav.status" as const, href: "/status" },
  { label: "Ranking", labelKey: "nav.ranking" as const, href: "/ranking" },
  { label: "Discuss", labelKey: "nav.discuss" as const, href: "/discuss" },
];

export const problems = [
  {
    id: "P1001",
    title: "A + B Problem",
    titleZh: "A + B 问题",
    difficulty: "Beginner",
    tags: ["math", "io"],
    accepted: "91.2%",
    submissions: "184k",
    timeLimit: "1s",
    memoryLimit: "256 MiB",
    statement: "Read two integers and print their sum.",
    statementZh: "读入两个整数，输出它们的和。",
    input: "1 2",
    output: "3",
  },
  {
    id: "P1024",
    title: "Prefix Sakura Trail",
    titleZh: "前缀和樱花小径",
    difficulty: "Easy",
    tags: ["prefix", "array"],
    accepted: "64.8%",
    submissions: "12k",
    timeLimit: "1s",
    memoryLimit: "256 MiB",
    statement: "Given an array, answer range sum queries with prefix sums.",
    statementZh: "给定一个数组，使用前缀和回答区间求和查询。",
    input: "5 2\n1 2 3 4 5\n1 3\n2 5",
    output: "6\n14",
  },
  {
    id: "P2048",
    title: "Rin and Dynamic Scoreboard",
    titleZh: "Rin 与动态排行榜",
    difficulty: "Medium",
    tags: ["heap", "greedy"],
    accepted: "38.5%",
    submissions: "7.8k",
    timeLimit: "2s",
    memoryLimit: "512 MiB",
    statement: "Maintain a live scoreboard while teams submit solutions.",
    statementZh: "在队伍不断提交代码时，维护实时排行榜。",
    input: "3 4\nA 100\nB 80\nA 30\nC 60",
    output: "A\nA\nA\nA",
  },
  {
    id: "P4096",
    title: "Moonlit Network Flow",
    titleZh: "月夜网络流",
    difficulty: "Hard",
    tags: ["flow", "graph"],
    accepted: "18.4%",
    submissions: "2.1k",
    timeLimit: "3s",
    memoryLimit: "1024 MiB",
    statement: "Compute the maximum flow in a directed graph.",
    statementZh: "计算有向图中的最大流。",
    input: "4 5\n1 2 3\n1 3 2\n2 3 1\n2 4 2\n3 4 4",
    output: "5",
  },
  {
    id: "P8192",
    title: "Interactive Tea Party",
    titleZh: "交互茶会",
    difficulty: "Expert",
    tags: ["interactive"],
    accepted: "9.7%",
    submissions: "806",
    timeLimit: "2s",
    memoryLimit: "256 MiB",
    statement: "Find the hidden number through an interactive protocol.",
    statementZh: "通过交互协议找到隐藏数字。",
    input: "interactive",
    output: "interactive",
  },
];

export const contests = [
  {
    id: "C1001",
    title: "Rin Weekly Round 12",
    titleZh: "Rin 周赛 12",
    mode: "ICPC",
    time: "Today 20:00",
    timeZh: "今天 20:00",
    registered: 428,
    status: "Registering",
  },
  {
    id: "C1002",
    title: "Spring Training Mirror",
    titleZh: "春季训练镜像赛",
    mode: "OI",
    time: "May 04 14:00",
    timeZh: "5 月 4 日 14:00",
    registered: 96,
    status: "Scheduled",
  },
  {
    id: "C1003",
    title: "AtCoder-style Practice",
    titleZh: "AtCoder 风格练习赛",
    mode: "AtCoder",
    time: "May 06 19:30",
    timeZh: "5 月 6 日 19:30",
    registered: 215,
    status: "Scheduled",
  },
];

export const contestProblems = [
  { contestId: "C1001", problemId: "P1001", alias: "A", points: 100 },
  { contestId: "C1001", problemId: "P1024", alias: "B", points: 100 },
  { contestId: "C1001", problemId: "P2048", alias: "C", points: 100 },
  { contestId: "C1002", problemId: "P1024", alias: "A", points: 100 },
  { contestId: "C1002", problemId: "P4096", alias: "B", points: 100 },
  { contestId: "C1003", problemId: "P1001", alias: "A", points: 500 },
  { contestId: "C1003", problemId: "P8192", alias: "B", points: 600 },
];

export const contestStandings = [
  { contestId: "C1001", rank: 1, user: "nanami", solved: 3, penalty: 218, score: 300 },
  { contestId: "C1001", rank: 2, user: "mika", solved: 2, penalty: 174, score: 200 },
  { contestId: "C1001", rank: 3, user: "sora", solved: 1, penalty: 96, score: 100 },
  { contestId: "C1002", rank: 1, user: "haru", solved: 2, penalty: 141, score: 200 },
  { contestId: "C1002", rank: 2, user: "akira", solved: 1, penalty: 87, score: 100 },
  { contestId: "C1003", rank: 1, user: "rin_admin", solved: 2, penalty: 0, score: 1100 },
  { contestId: "C1003", rank: 2, user: "yuki", solved: 1, penalty: 0, score: 500 },
];

export const judgements = [
  { when: "12s ago", whenZh: "12 秒前", user: "mika", problem: "P1024", lang: "C++20", verdict: "Accepted", time: "31 ms", memory: "6.4 MiB" },
  { when: "28s ago", whenZh: "28 秒前", user: "yuki", problem: "P2048", lang: "Rust", verdict: "Wrong Answer", time: "44 ms", memory: "9.1 MiB" },
  { when: "43s ago", whenZh: "43 秒前", user: "akira", problem: "P1001", lang: "Go", verdict: "Accepted", time: "5 ms", memory: "2.2 MiB" },
  { when: "1m ago", whenZh: "1 分钟前", user: "sora", problem: "P4096", lang: "Python 3", verdict: "TLE", time: "1000 ms", memory: "42.0 MiB" },
  { when: "2m ago", whenZh: "2 分钟前", user: "haru", problem: "P1001", lang: "Java 17", verdict: "Accepted", time: "63 ms", memory: "32.0 MiB" },
  { when: "3m ago", whenZh: "3 分钟前", user: "nanami", problem: "P4096", lang: "C11", verdict: "Accepted", time: "22 ms", memory: "3.8 MiB" },
  { when: "4m ago", whenZh: "4 分钟前", user: "rin_admin", problem: "P1024", lang: "JavaScript", verdict: "Runtime Error", time: "18 ms", memory: "18.0 MiB" },
  { when: "5m ago", whenZh: "5 分钟前", user: "mika", problem: "P1001", lang: "PHP", verdict: "Accepted", time: "36 ms", memory: "12.4 MiB" },
];

export const ratingRows = [
  { rank: 1, name: "nanami", rating: 2416, solved: 318, motto: "flow enjoyer" },
  { rank: 2, name: "rin_admin", rating: 2388, solved: 302, motto: "keeps the judge warm" },
  { rank: 3, name: "haru", rating: 2294, solved: 277, motto: "dp before coffee" },
  { rank: 4, name: "mika", rating: 2160, solved: 241, motto: "one more submission" },
  { rank: 5, name: "sora", rating: 2058, solved: 226, motto: "graphs are poems" },
];

export const discussPosts = [
  {
    id: "D1001",
    type: "editorial",
    title: "A + B 的输入输出坑点整理",
    titleEn: "A + B input/output notes",
    author: "rin_admin",
    problemId: "P1001",
    createdAt: "8m ago",
    createdAtZh: "8 分钟前",
    replies: 12,
    likes: 48,
    excerpt: "题解里演示 fast I/O、换行和最小 C++17 写法。复杂度 $O(1)$。",
    excerptEn: "Editorial with fast I/O, newline handling, and a minimal C++17 solution. Complexity $O(1)$.",
    body: "## 思路\n读入两个整数 $a,b$，输出 $a+b$。\n\n```cpp\nint a, b;\ncin >> a >> b;\ncout << a + b << '\\n';\n```\n\n关联题目：P1001",
  },
  {
    id: "D1024",
    type: "editorial",
    title: "前缀和为什么能把区间查询降到 O(1)",
    titleEn: "Why prefix sums answer range queries in O(1)",
    author: "mika",
    problemId: "P1024",
    createdAt: "21m ago",
    createdAtZh: "21 分钟前",
    replies: 6,
    likes: 31,
    excerpt: "如果 $s_i=a_1+...+a_i$，那么区间和就是 $s_r-s_{l-1}$。",
    excerptEn: "If $s_i=a_1+...+a_i$, then range sum is $s_r-s_{l-1}$.",
    body: "## 公式\n$$sum(l,r)=prefix[r]-prefix[l-1]$$\n\n可以去看 P1024 的样例。",
  },
  {
    id: "D2048",
    type: "question",
    title: "动态排行榜这题用堆还是排序更稳？",
    titleEn: "Heap or sorting for the dynamic scoreboard problem?",
    author: "yuki",
    problemId: "P2048",
    createdAt: "34m ago",
    createdAtZh: "34 分钟前",
    replies: 9,
    likes: 18,
    excerpt: "我在 P2048 里每次排序会 TLE，想确认是不是应该维护堆或有序集合。",
    excerptEn: "Sorting every update in P2048 seems too slow. Should I maintain a heap or ordered set?",
    body: "每次提交后都 sort 一遍复杂度太高。\n\n想问：能不能维护一个 `priority_queue`？",
  },
];

export const userProfiles = [
  {
    username: "nanami",
    displayName: "Nanami",
    title: "Sakura Grandmaster",
    titleZh: "樱花宗师",
    rating: 2416,
    solved: 318,
    followers: 1280,
    streak: 42,
    signature: "flow enjoyer",
    signatureZh: "网络流爱好者",
    badges: ["ICPC", "Flow", "Teacher"],
    heatmap: [0, 1, 2, 3, 4, 2, 1, 0, 3, 4, 2, 1, 4, 3, 0, 2, 2, 4, 1, 3, 0, 1, 4, 2, 3, 2, 0, 1],
  },
  {
    username: "rin_admin",
    displayName: "Rin Admin",
    title: "Judge Keeper",
    titleZh: "评测守护者",
    rating: 2388,
    solved: 302,
    followers: 910,
    streak: 36,
    signature: "keeps the judge warm",
    signatureZh: "让评测机保持温暖",
    badges: ["Admin", "go-judge", "Ops"],
    heatmap: [2, 2, 3, 4, 4, 1, 0, 3, 3, 2, 4, 1, 2, 0, 3, 4, 4, 2, 1, 2, 3, 4, 0, 2, 1, 4, 3, 2],
  },
  {
    username: "mika",
    displayName: "Mika",
    title: "Prefix Runner",
    titleZh: "前缀和旅人",
    rating: 2160,
    solved: 241,
    followers: 512,
    streak: 18,
    signature: "one more submission",
    signatureZh: "再交一次就过",
    badges: ["Array", "Greedy", "Weekly"],
    heatmap: [0, 0, 1, 2, 3, 0, 1, 2, 4, 1, 0, 3, 2, 1, 4, 0, 2, 3, 1, 1, 4, 2, 0, 3, 1, 2, 4, 0],
  },
  {
    username: "haru",
    displayName: "Haru",
    title: "DP Crafter",
    titleZh: "动态规划匠人",
    rating: 2294,
    solved: 277,
    followers: 720,
    streak: 31,
    signature: "dp before coffee",
    signatureZh: "咖啡之前先 DP",
    badges: ["DP", "OI", "Editorial"],
    heatmap: [2, 3, 4, 1, 2, 0, 3, 4, 1, 2, 3, 0, 4, 2, 1, 3, 4, 0, 2, 1, 3, 4, 2, 0, 1, 3, 2, 4],
  },
  {
    username: "sora",
    displayName: "Sora",
    title: "Graph Poet",
    titleZh: "图论诗人",
    rating: 2058,
    solved: 226,
    followers: 404,
    streak: 15,
    signature: "graphs are poems",
    signatureZh: "图也是诗",
    badges: ["Graph", "DFS", "Contest"],
    heatmap: [1, 2, 0, 1, 3, 4, 2, 0, 1, 2, 3, 1, 0, 4, 2, 2, 1, 3, 0, 2, 4, 1, 3, 0, 2, 1, 3, 4],
  },
  {
    username: "yuki",
    displayName: "Yuki",
    title: "Rust Learner",
    titleZh: "Rust 修行者",
    rating: 1964,
    solved: 198,
    followers: 260,
    streak: 9,
    signature: "borrow checker arc",
    signatureZh: "正在和借用检查器修行",
    badges: ["Rust", "DP", "Practice"],
    heatmap: [0, 1, 1, 2, 0, 3, 2, 1, 0, 2, 4, 1, 2, 3, 0, 1, 2, 0, 3, 4, 1, 2, 1, 0, 3, 2, 1, 4],
  },
  {
    username: "akira",
    displayName: "Akira",
    title: "Go Sprinter",
    titleZh: "Go 语言冲刺者",
    rating: 1880,
    solved: 176,
    followers: 190,
    streak: 7,
    signature: "tiny code, fast AC",
    signatureZh: "短代码，快 AC",
    badges: ["Go", "Beginner", "Sprint"],
    heatmap: [1, 0, 2, 1, 0, 2, 3, 1, 4, 0, 1, 2, 2, 0, 3, 1, 2, 4, 0, 1, 3, 2, 0, 1, 4, 2, 1, 0],
  },
];
