// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rin/submission/v1/submission.proto

package submissionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmissionStatus int32

const (
	SubmissionStatus_SUBMISSION_STATUS_UNSPECIFIED           SubmissionStatus = 0
	SubmissionStatus_SUBMISSION_STATUS_QUEUED                SubmissionStatus = 1
	SubmissionStatus_SUBMISSION_STATUS_COMPILING             SubmissionStatus = 2
	SubmissionStatus_SUBMISSION_STATUS_RUNNING               SubmissionStatus = 3
	SubmissionStatus_SUBMISSION_STATUS_ACCEPTED              SubmissionStatus = 4
	SubmissionStatus_SUBMISSION_STATUS_WRONG_ANSWER          SubmissionStatus = 5
	SubmissionStatus_SUBMISSION_STATUS_TIME_LIMIT_EXCEEDED   SubmissionStatus = 6
	SubmissionStatus_SUBMISSION_STATUS_MEMORY_LIMIT_EXCEEDED SubmissionStatus = 7
	SubmissionStatus_SUBMISSION_STATUS_RUNTIME_ERROR         SubmissionStatus = 8
	SubmissionStatus_SUBMISSION_STATUS_COMPILE_ERROR         SubmissionStatus = 9
	SubmissionStatus_SUBMISSION_STATUS_SYSTEM_ERROR          SubmissionStatus = 10
)

// Enum value maps for SubmissionStatus.
var (
	SubmissionStatus_name = map[int32]string{
		0:  "SUBMISSION_STATUS_UNSPECIFIED",
		1:  "SUBMISSION_STATUS_QUEUED",
		2:  "SUBMISSION_STATUS_COMPILING",
		3:  "SUBMISSION_STATUS_RUNNING",
		4:  "SUBMISSION_STATUS_ACCEPTED",
		5:  "SUBMISSION_STATUS_WRONG_ANSWER",
		6:  "SUBMISSION_STATUS_TIME_LIMIT_EXCEEDED",
		7:  "SUBMISSION_STATUS_MEMORY_LIMIT_EXCEEDED",
		8:  "SUBMISSION_STATUS_RUNTIME_ERROR",
		9:  "SUBMISSION_STATUS_COMPILE_ERROR",
		10: "SUBMISSION_STATUS_SYSTEM_ERROR",
	}
	SubmissionStatus_value = map[string]int32{
		"SUBMISSION_STATUS_UNSPECIFIED":           0,
		"SUBMISSION_STATUS_QUEUED":                1,
		"SUBMISSION_STATUS_COMPILING":             2,
		"SUBMISSION_STATUS_RUNNING":               3,
		"SUBMISSION_STATUS_ACCEPTED":              4,
		"SUBMISSION_STATUS_WRONG_ANSWER":          5,
		"SUBMISSION_STATUS_TIME_LIMIT_EXCEEDED":   6,
		"SUBMISSION_STATUS_MEMORY_LIMIT_EXCEEDED": 7,
		"SUBMISSION_STATUS_RUNTIME_ERROR":         8,
		"SUBMISSION_STATUS_COMPILE_ERROR":         9,
		"SUBMISSION_STATUS_SYSTEM_ERROR":          10,
	}
)

func (x SubmissionStatus) Enum() *SubmissionStatus {
	p := new(SubmissionStatus)
	*p = x
	return p
}

func (x SubmissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rin_submission_v1_submission_proto_enumTypes[0].Descriptor()
}

func (SubmissionStatus) Type() protoreflect.EnumType {
	return &file_rin_submission_v1_submission_proto_enumTypes[0]
}

func (x SubmissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubmissionStatus.Descriptor instead.
func (SubmissionStatus) EnumDescriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{0}
}

type CreateSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ProblemId     string                 `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ContestId     string                 `protobuf:"bytes,3,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	LanguageId    string                 `protobuf:"bytes,4,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	SourceCode    string                 `protobuf:"bytes,5,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubmissionRequest) Reset() {
	*x = CreateSubmissionRequest{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubmissionRequest) ProtoMessage() {}

func (x *CreateSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubmissionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubmissionRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CreateSubmissionRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *CreateSubmissionRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *CreateSubmissionRequest) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *CreateSubmissionRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

type Submission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ProblemId     string                 `protobuf:"bytes,3,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ContestId     string                 `protobuf:"bytes,4,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	LanguageId    string                 `protobuf:"bytes,5,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	Status        SubmissionStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=rin.submission.v1.SubmissionStatus" json:"status,omitempty"`
	Score         int64                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{1}
}

func (x *Submission) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *Submission) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Submission) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *Submission) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *Submission) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *Submission) GetStatus() SubmissionStatus {
	if x != nil {
		return x.Status
	}
	return SubmissionStatus_SUBMISSION_STATUS_UNSPECIFIED
}

func (x *Submission) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Submission) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type GetSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionRequest) Reset() {
	*x = GetSubmissionRequest{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionRequest) ProtoMessage() {}

func (x *GetSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionRequest.ProtoReflect.Descriptor instead.
func (*GetSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubmissionRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

type ListSubmissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ProblemId     string                 `protobuf:"bytes,4,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ContestId     string                 `protobuf:"bytes,5,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubmissionsRequest) Reset() {
	*x = ListSubmissionsRequest{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubmissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsRequest) ProtoMessage() {}

func (x *ListSubmissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubmissionsRequest) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{3}
}

func (x *ListSubmissionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListSubmissionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSubmissionsRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ListSubmissionsRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *ListSubmissionsRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

type ListSubmissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submissions   []*Submission          `protobuf:"bytes,1,rep,name=submissions,proto3" json:"submissions,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubmissionsResponse) Reset() {
	*x = ListSubmissionsResponse{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubmissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsResponse) ProtoMessage() {}

func (x *ListSubmissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubmissionsResponse) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{4}
}

func (x *ListSubmissionsResponse) GetSubmissions() []*Submission {
	if x != nil {
		return x.Submissions
	}
	return nil
}

func (x *ListSubmissionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type StreamSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSubmissionRequest) Reset() {
	*x = StreamSubmissionRequest{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSubmissionRequest) ProtoMessage() {}

func (x *StreamSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSubmissionRequest.ProtoReflect.Descriptor instead.
func (*StreamSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{5}
}

func (x *StreamSubmissionRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

type SubmissionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Status        SubmissionStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=rin.submission.v1.SubmissionStatus" json:"status,omitempty"`
	TestCaseIndex int32                  `protobuf:"varint,3,opt,name=test_case_index,json=testCaseIndex,proto3" json:"test_case_index,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	TimeMs        int64                  `protobuf:"varint,5,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Final         bool                   `protobuf:"varint,7,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionEvent) Reset() {
	*x = SubmissionEvent{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionEvent) ProtoMessage() {}

func (x *SubmissionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionEvent.ProtoReflect.Descriptor instead.
func (*SubmissionEvent) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{6}
}

func (x *SubmissionEvent) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *SubmissionEvent) GetStatus() SubmissionStatus {
	if x != nil {
		return x.Status
	}
	return SubmissionStatus_SUBMISSION_STATUS_UNSPECIFIED
}

func (x *SubmissionEvent) GetTestCaseIndex() int32 {
	if x != nil {
		return x.TestCaseIndex
	}
	return 0
}

func (x *SubmissionEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmissionEvent) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *SubmissionEvent) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *SubmissionEvent) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type ReportJudgeResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Status        SubmissionStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=rin.submission.v1.SubmissionStatus" json:"status,omitempty"`
	TestCaseIndex int32                  `protobuf:"varint,3,opt,name=test_case_index,json=testCaseIndex,proto3" json:"test_case_index,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	TimeMs        int64                  `protobuf:"varint,5,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Final         bool                   `protobuf:"varint,7,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJudgeResultRequest) Reset() {
	*x = ReportJudgeResultRequest{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJudgeResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJudgeResultRequest) ProtoMessage() {}

func (x *ReportJudgeResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJudgeResultRequest.ProtoReflect.Descriptor instead.
func (*ReportJudgeResultRequest) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{7}
}

func (x *ReportJudgeResultRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *ReportJudgeResultRequest) GetStatus() SubmissionStatus {
	if x != nil {
		return x.Status
	}
	return SubmissionStatus_SUBMISSION_STATUS_UNSPECIFIED
}

func (x *ReportJudgeResultRequest) GetTestCaseIndex() int32 {
	if x != nil {
		return x.TestCaseIndex
	}
	return 0
}

func (x *ReportJudgeResultRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportJudgeResultRequest) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *ReportJudgeResultRequest) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ReportJudgeResultRequest) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type ReportJudgeResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *Submission            `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJudgeResultResponse) Reset() {
	*x = ReportJudgeResultResponse{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJudgeResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJudgeResultResponse) ProtoMessage() {}

func (x *ReportJudgeResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJudgeResultResponse.ProtoReflect.Descriptor instead.
func (*ReportJudgeResultResponse) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{8}
}

func (x *ReportJudgeResultResponse) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type RejudgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	SubmissionIds []string               `protobuf:"bytes,2,rep,name=submission_ids,json=submissionIds,proto3" json:"submission_ids,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejudgeRequest) Reset() {
	*x = RejudgeRequest{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejudgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejudgeRequest) ProtoMessage() {}

func (x *RejudgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejudgeRequest.ProtoReflect.Descriptor instead.
func (*RejudgeRequest) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{9}
}

func (x *RejudgeRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RejudgeRequest) GetSubmissionIds() []string {
	if x != nil {
		return x.SubmissionIds
	}
	return nil
}

func (x *RejudgeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejudgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnqueuedCount int64                  `protobuf:"varint,1,opt,name=enqueued_count,json=enqueuedCount,proto3" json:"enqueued_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejudgeResponse) Reset() {
	*x = RejudgeResponse{}
	mi := &file_rin_submission_v1_submission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejudgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejudgeResponse) ProtoMessage() {}

func (x *RejudgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rin_submission_v1_submission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejudgeResponse.ProtoReflect.Descriptor instead.
func (*RejudgeResponse) Descriptor() ([]byte, []int) {
	return file_rin_submission_v1_submission_proto_rawDescGZIP(), []int{10}
}

func (x *RejudgeResponse) GetEnqueuedCount() int64 {
	if x != nil {
		return x.EnqueuedCount
	}
	return 0
}

var File_rin_submission_v1_submission_proto protoreflect.FileDescriptor

const file_rin_submission_v1_submission_proto_rawDesc = "" +
	"\n" +
	"\"rin/submission/v1/submission.proto\x12\x11rin.submission.v1\"\xb4\x01\n" +
	"\x17CreateSubmissionRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\tR\tproblemId\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x03 \x01(\tR\tcontestId\x12\x1f\n" +
	"\vlanguage_id\x18\x04 \x01(\tR\n" +
	"languageId\x12\x1f\n" +
	"\vsource_code\x18\x05 \x01(\tR\n" +
	"sourceCode\"\xa6\x02\n" +
	"\n" +
	"Submission\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x03 \x01(\tR\tproblemId\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x04 \x01(\tR\tcontestId\x12\x1f\n" +
	"\vlanguage_id\x18\x05 \x01(\tR\n" +
	"languageId\x12;\n" +
	"\x06status\x18\x06 \x01(\x0e2#.rin.submission.v1.SubmissionStatusR\x06status\x12\x14\n" +
	"\x05score\x18\a \x01(\x03R\x05score\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\";\n" +
	"\x14GetSubmissionRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\"\xa6\x01\n" +
	"\x16ListSubmissionsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x04 \x01(\tR\tproblemId\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x05 \x01(\tR\tcontestId\"{\n" +
	"\x17ListSubmissionsResponse\x12?\n" +
	"\vsubmissions\x18\x01 \x03(\v2\x1d.rin.submission.v1.SubmissionR\vsubmissions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\">\n" +
	"\x17StreamSubmissionRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\"\x87\x02\n" +
	"\x0fSubmissionEvent\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.rin.submission.v1.SubmissionStatusR\x06status\x12&\n" +
	"\x0ftest_case_index\x18\x03 \x01(\x05R\rtestCaseIndex\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x17\n" +
	"\atime_ms\x18\x05 \x01(\x03R\x06timeMs\x12!\n" +
	"\fmemory_bytes\x18\x06 \x01(\x03R\vmemoryBytes\x12\x14\n" +
	"\x05final\x18\a \x01(\bR\x05final\"\x90\x02\n" +
	"\x18ReportJudgeResultRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.rin.submission.v1.SubmissionStatusR\x06status\x12&\n" +
	"\x0ftest_case_index\x18\x03 \x01(\x05R\rtestCaseIndex\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x17\n" +
	"\atime_ms\x18\x05 \x01(\x03R\x06timeMs\x12!\n" +
	"\fmemory_bytes\x18\x06 \x01(\x03R\vmemoryBytes\x12\x14\n" +
	"\x05final\x18\a \x01(\bR\x05final\"Z\n" +
	"\x19ReportJudgeResultResponse\x12=\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x1d.rin.submission.v1.SubmissionR\n" +
	"submission\"j\n" +
	"\x0eRejudgeRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12%\n" +
	"\x0esubmission_ids\x18\x02 \x03(\tR\rsubmissionIds\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"8\n" +
	"\x0fRejudgeResponse\x12%\n" +
	"\x0eenqueued_count\x18\x01 \x01(\x03R\renqueuedCount*\x9d\x03\n" +
	"\x10SubmissionStatus\x12!\n" +
	"\x1dSUBMISSION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SUBMISSION_STATUS_QUEUED\x10\x01\x12\x1f\n" +
	"\x1bSUBMISSION_STATUS_COMPILING\x10\x02\x12\x1d\n" +
	"\x19SUBMISSION_STATUS_RUNNING\x10\x03\x12\x1e\n" +
	"\x1aSUBMISSION_STATUS_ACCEPTED\x10\x04\x12\"\n" +
	"\x1eSUBMISSION_STATUS_WRONG_ANSWER\x10\x05\x12)\n" +
	"%SUBMISSION_STATUS_TIME_LIMIT_EXCEEDED\x10\x06\x12+\n" +
	"'SUBMISSION_STATUS_MEMORY_LIMIT_EXCEEDED\x10\a\x12#\n" +
	"\x1fSUBMISSION_STATUS_RUNTIME_ERROR\x10\b\x12#\n" +
	"\x1fSUBMISSION_STATUS_COMPILE_ERROR\x10\t\x12\"\n" +
	"\x1eSUBMISSION_STATUS_SYSTEM_ERROR\x10\n" +
	"2\xdd\x04\n" +
	"\x11SubmissionService\x12]\n" +
	"\x10CreateSubmission\x12*.rin.submission.v1.CreateSubmissionRequest\x1a\x1d.rin.submission.v1.Submission\x12W\n" +
	"\rGetSubmission\x12'.rin.submission.v1.GetSubmissionRequest\x1a\x1d.rin.submission.v1.Submission\x12h\n" +
	"\x0fListSubmissions\x12).rin.submission.v1.ListSubmissionsRequest\x1a*.rin.submission.v1.ListSubmissionsResponse\x12d\n" +
	"\x10StreamSubmission\x12*.rin.submission.v1.StreamSubmissionRequest\x1a\".rin.submission.v1.SubmissionEvent0\x01\x12n\n" +
	"\x11ReportJudgeResult\x12+.rin.submission.v1.ReportJudgeResultRequest\x1a,.rin.submission.v1.ReportJudgeResultResponse\x12P\n" +
	"\aRejudge\x12!.rin.submission.v1.RejudgeRequest\x1a\".rin.submission.v1.RejudgeResponseBIZGgithub.com/rin-oj/rin-oj/packages/sdk-go/rin/submission/v1;submissionv1b\x06proto3"

var (
	file_rin_submission_v1_submission_proto_rawDescOnce sync.Once
	file_rin_submission_v1_submission_proto_rawDescData []byte
)

func file_rin_submission_v1_submission_proto_rawDescGZIP() []byte {
	file_rin_submission_v1_submission_proto_rawDescOnce.Do(func() {
		file_rin_submission_v1_submission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rin_submission_v1_submission_proto_rawDesc), len(file_rin_submission_v1_submission_proto_rawDesc)))
	})
	return file_rin_submission_v1_submission_proto_rawDescData
}

var file_rin_submission_v1_submission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rin_submission_v1_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rin_submission_v1_submission_proto_goTypes = []any{
	(SubmissionStatus)(0),             // 0: rin.submission.v1.SubmissionStatus
	(*CreateSubmissionRequest)(nil),   // 1: rin.submission.v1.CreateSubmissionRequest
	(*Submission)(nil),                // 2: rin.submission.v1.Submission
	(*GetSubmissionRequest)(nil),      // 3: rin.submission.v1.GetSubmissionRequest
	(*ListSubmissionsRequest)(nil),    // 4: rin.submission.v1.ListSubmissionsRequest
	(*ListSubmissionsResponse)(nil),   // 5: rin.submission.v1.ListSubmissionsResponse
	(*StreamSubmissionRequest)(nil),   // 6: rin.submission.v1.StreamSubmissionRequest
	(*SubmissionEvent)(nil),           // 7: rin.submission.v1.SubmissionEvent
	(*ReportJudgeResultRequest)(nil),  // 8: rin.submission.v1.ReportJudgeResultRequest
	(*ReportJudgeResultResponse)(nil), // 9: rin.submission.v1.ReportJudgeResultResponse
	(*RejudgeRequest)(nil),            // 10: rin.submission.v1.RejudgeRequest
	(*RejudgeResponse)(nil),           // 11: rin.submission.v1.RejudgeResponse
}
var file_rin_submission_v1_submission_proto_depIdxs = []int32{
	0,  // 0: rin.submission.v1.Submission.status:type_name -> rin.submission.v1.SubmissionStatus
	2,  // 1: rin.submission.v1.ListSubmissionsResponse.submissions:type_name -> rin.submission.v1.Submission
	0,  // 2: rin.submission.v1.SubmissionEvent.status:type_name -> rin.submission.v1.SubmissionStatus
	0,  // 3: rin.submission.v1.ReportJudgeResultRequest.status:type_name -> rin.submission.v1.SubmissionStatus
	2,  // 4: rin.submission.v1.ReportJudgeResultResponse.submission:type_name -> rin.submission.v1.Submission
	1,  // 5: rin.submission.v1.SubmissionService.CreateSubmission:input_type -> rin.submission.v1.CreateSubmissionRequest
	3,  // 6: rin.submission.v1.SubmissionService.GetSubmission:input_type -> rin.submission.v1.GetSubmissionRequest
	4,  // 7: rin.submission.v1.SubmissionService.ListSubmissions:input_type -> rin.submission.v1.ListSubmissionsRequest
	6,  // 8: rin.submission.v1.SubmissionService.StreamSubmission:input_type -> rin.submission.v1.StreamSubmissionRequest
	8,  // 9: rin.submission.v1.SubmissionService.ReportJudgeResult:input_type -> rin.submission.v1.ReportJudgeResultRequest
	10, // 10: rin.submission.v1.SubmissionService.Rejudge:input_type -> rin.submission.v1.RejudgeRequest
	2,  // 11: rin.submission.v1.SubmissionService.CreateSubmission:output_type -> rin.submission.v1.Submission
	2,  // 12: rin.submission.v1.SubmissionService.GetSubmission:output_type -> rin.submission.v1.Submission
	5,  // 13: rin.submission.v1.SubmissionService.ListSubmissions:output_type -> rin.submission.v1.ListSubmissionsResponse
	7,  // 14: rin.submission.v1.SubmissionService.StreamSubmission:output_type -> rin.submission.v1.SubmissionEvent
	9,  // 15: rin.submission.v1.SubmissionService.ReportJudgeResult:output_type -> rin.submission.v1.ReportJudgeResultResponse
	11, // 16: rin.submission.v1.SubmissionService.Rejudge:output_type -> rin.submission.v1.RejudgeResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rin_submission_v1_submission_proto_init() }
func file_rin_submission_v1_submission_proto_init() {
	if File_rin_submission_v1_submission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rin_submission_v1_submission_proto_rawDesc), len(file_rin_submission_v1_submission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rin_submission_v1_submission_proto_goTypes,
		DependencyIndexes: file_rin_submission_v1_submission_proto_depIdxs,
		EnumInfos:         file_rin_submission_v1_submission_proto_enumTypes,
		MessageInfos:      file_rin_submission_v1_submission_proto_msgTypes,
	}.Build()
	File_rin_submission_v1_submission_proto = out.File
	file_rin_submission_v1_submission_proto_goTypes = nil
	file_rin_submission_v1_submission_proto_depIdxs = nil
}
