// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rin/event/v1/event.proto

package eventv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version        int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,4,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	ActorId        string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	SubjectId      string                 `protobuf:"bytes,6,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	TraceId        string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	PayloadJson    []byte                 `protobuf:"bytes,8,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_rin_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_rin_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_rin_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EventEnvelope) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

func (x *EventEnvelope) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *EventEnvelope) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *EventEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventEnvelope) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_rin_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rin_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_rin_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *PublishEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumer      string                 `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_rin_event_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_event_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_rin_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_rin_event_v1_event_proto protoreflect.FileDescriptor

const file_rin_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x18rin/event/v1/event.proto\x12\frin.event.v1\"\xef\x01\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12(\n" +
	"\x10occurred_at_unix\x18\x04 \x01(\x03R\x0eoccurredAtUnix\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x06 \x01(\tR\tsubjectId\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12!\n" +
	"\fpayload_json\x18\b \x01(\fR\vpayloadJson\"1\n" +
	"\x14PublishEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"F\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\bconsumer\x18\x01 \x01(\tR\bconsumer\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics2\xa9\x01\n" +
	"\x0fEventBusService\x12J\n" +
	"\aPublish\x12\x1b.rin.event.v1.EventEnvelope\x1a\".rin.event.v1.PublishEventResponse\x12J\n" +
	"\tSubscribe\x12\x1e.rin.event.v1.SubscribeRequest\x1a\x1b.rin.event.v1.EventEnvelope0\x01B?Z=github.com/rin-oj/rin-oj/packages/sdk-go/rin/event/v1;eventv1b\x06proto3"

var (
	file_rin_event_v1_event_proto_rawDescOnce sync.Once
	file_rin_event_v1_event_proto_rawDescData []byte
)

func file_rin_event_v1_event_proto_rawDescGZIP() []byte {
	file_rin_event_v1_event_proto_rawDescOnce.Do(func() {
		file_rin_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rin_event_v1_event_proto_rawDesc), len(file_rin_event_v1_event_proto_rawDesc)))
	})
	return file_rin_event_v1_event_proto_rawDescData
}

var file_rin_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rin_event_v1_event_proto_goTypes = []any{
	(*EventEnvelope)(nil),        // 0: rin.event.v1.EventEnvelope
	(*PublishEventResponse)(nil), // 1: rin.event.v1.PublishEventResponse
	(*SubscribeRequest)(nil),     // 2: rin.event.v1.SubscribeRequest
}
var file_rin_event_v1_event_proto_depIdxs = []int32{
	0, // 0: rin.event.v1.EventBusService.Publish:input_type -> rin.event.v1.EventEnvelope
	2, // 1: rin.event.v1.EventBusService.Subscribe:input_type -> rin.event.v1.SubscribeRequest
	1, // 2: rin.event.v1.EventBusService.Publish:output_type -> rin.event.v1.PublishEventResponse
	0, // 3: rin.event.v1.EventBusService.Subscribe:output_type -> rin.event.v1.EventEnvelope
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rin_event_v1_event_proto_init() }
func file_rin_event_v1_event_proto_init() {
	if File_rin_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rin_event_v1_event_proto_rawDesc), len(file_rin_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rin_event_v1_event_proto_goTypes,
		DependencyIndexes: file_rin_event_v1_event_proto_depIdxs,
		MessageInfos:      file_rin_event_v1_event_proto_msgTypes,
	}.Build()
	File_rin_event_v1_event_proto = out.File
	file_rin_event_v1_event_proto_goTypes = nil
	file_rin_event_v1_event_proto_depIdxs = nil
}
