// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: rin/contest/v1/contest.proto

package contestv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContestService_CreateContest_FullMethodName    = "/rin.contest.v1.ContestService/CreateContest"
	ContestService_RegisterContest_FullMethodName  = "/rin.contest.v1.ContestService/RegisterContest"
	ContestService_GetScoreboard_FullMethodName    = "/rin.contest.v1.ContestService/GetScoreboard"
	ContestService_StreamScoreboard_FullMethodName = "/rin.contest.v1.ContestService/StreamScoreboard"
)

// ContestServiceClient is the client API for ContestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContestServiceClient interface {
	CreateContest(ctx context.Context, in *CreateContestRequest, opts ...grpc.CallOption) (*Contest, error)
	RegisterContest(ctx context.Context, in *RegisterContestRequest, opts ...grpc.CallOption) (*ContestRegistration, error)
	GetScoreboard(ctx context.Context, in *GetScoreboardRequest, opts ...grpc.CallOption) (*Scoreboard, error)
	StreamScoreboard(ctx context.Context, in *StreamScoreboardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScoreboardEvent], error)
}

type contestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContestServiceClient(cc grpc.ClientConnInterface) ContestServiceClient {
	return &contestServiceClient{cc}
}

func (c *contestServiceClient) CreateContest(ctx context.Context, in *CreateContestRequest, opts ...grpc.CallOption) (*Contest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Contest)
	err := c.cc.Invoke(ctx, ContestService_CreateContest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contestServiceClient) RegisterContest(ctx context.Context, in *RegisterContestRequest, opts ...grpc.CallOption) (*ContestRegistration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContestRegistration)
	err := c.cc.Invoke(ctx, ContestService_RegisterContest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contestServiceClient) GetScoreboard(ctx context.Context, in *GetScoreboardRequest, opts ...grpc.CallOption) (*Scoreboard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scoreboard)
	err := c.cc.Invoke(ctx, ContestService_GetScoreboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contestServiceClient) StreamScoreboard(ctx context.Context, in *StreamScoreboardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScoreboardEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContestService_ServiceDesc.Streams[0], ContestService_StreamScoreboard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamScoreboardRequest, ScoreboardEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContestService_StreamScoreboardClient = grpc.ServerStreamingClient[ScoreboardEvent]

// ContestServiceServer is the server API for ContestService service.
// All implementations must embed UnimplementedContestServiceServer
// for forward compatibility.
type ContestServiceServer interface {
	CreateContest(context.Context, *CreateContestRequest) (*Contest, error)
	RegisterContest(context.Context, *RegisterContestRequest) (*ContestRegistration, error)
	GetScoreboard(context.Context, *GetScoreboardRequest) (*Scoreboard, error)
	StreamScoreboard(*StreamScoreboardRequest, grpc.ServerStreamingServer[ScoreboardEvent]) error
	mustEmbedUnimplementedContestServiceServer()
}

// UnimplementedContestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContestServiceServer struct{}

func (UnimplementedContestServiceServer) CreateContest(context.Context, *CreateContestRequest) (*Contest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContest not implemented")
}
func (UnimplementedContestServiceServer) RegisterContest(context.Context, *RegisterContestRequest) (*ContestRegistration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterContest not implemented")
}
func (UnimplementedContestServiceServer) GetScoreboard(context.Context, *GetScoreboardRequest) (*Scoreboard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoreboard not implemented")
}
func (UnimplementedContestServiceServer) StreamScoreboard(*StreamScoreboardRequest, grpc.ServerStreamingServer[ScoreboardEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamScoreboard not implemented")
}
func (UnimplementedContestServiceServer) mustEmbedUnimplementedContestServiceServer() {}
func (UnimplementedContestServiceServer) testEmbeddedByValue()                        {}

// UnsafeContestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContestServiceServer will
// result in compilation errors.
type UnsafeContestServiceServer interface {
	mustEmbedUnimplementedContestServiceServer()
}

func RegisterContestServiceServer(s grpc.ServiceRegistrar, srv ContestServiceServer) {
	// If the following call pancis, it indicates UnimplementedContestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContestService_ServiceDesc, srv)
}

func _ContestService_CreateContest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContestServiceServer).CreateContest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContestService_CreateContest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContestServiceServer).CreateContest(ctx, req.(*CreateContestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContestService_RegisterContest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterContestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContestServiceServer).RegisterContest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContestService_RegisterContest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContestServiceServer).RegisterContest(ctx, req.(*RegisterContestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContestService_GetScoreboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoreboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContestServiceServer).GetScoreboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContestService_GetScoreboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContestServiceServer).GetScoreboard(ctx, req.(*GetScoreboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContestService_StreamScoreboard_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamScoreboardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContestServiceServer).StreamScoreboard(m, &grpc.GenericServerStream[StreamScoreboardRequest, ScoreboardEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContestService_StreamScoreboardServer = grpc.ServerStreamingServer[ScoreboardEvent]

// ContestService_ServiceDesc is the grpc.ServiceDesc for ContestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rin.contest.v1.ContestService",
	HandlerType: (*ContestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContest",
			Handler:    _ContestService_CreateContest_Handler,
		},
		{
			MethodName: "RegisterContest",
			Handler:    _ContestService_RegisterContest_Handler,
		},
		{
			MethodName: "GetScoreboard",
			Handler:    _ContestService_GetScoreboard_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamScoreboard",
			Handler:       _ContestService_StreamScoreboard_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rin/contest/v1/contest.proto",
}
