// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rin/contest/v1/contest.proto

package contestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContestMode int32

const (
	ContestMode_CONTEST_MODE_UNSPECIFIED ContestMode = 0
	ContestMode_CONTEST_MODE_ACM         ContestMode = 1
	ContestMode_CONTEST_MODE_IOI         ContestMode = 2
	ContestMode_CONTEST_MODE_OI          ContestMode = 3
	ContestMode_CONTEST_MODE_CODEFORCES  ContestMode = 4
	ContestMode_CONTEST_MODE_ATCODER     ContestMode = 5
)

// Enum value maps for ContestMode.
var (
	ContestMode_name = map[int32]string{
		0: "CONTEST_MODE_UNSPECIFIED",
		1: "CONTEST_MODE_ACM",
		2: "CONTEST_MODE_IOI",
		3: "CONTEST_MODE_OI",
		4: "CONTEST_MODE_CODEFORCES",
		5: "CONTEST_MODE_ATCODER",
	}
	ContestMode_value = map[string]int32{
		"CONTEST_MODE_UNSPECIFIED": 0,
		"CONTEST_MODE_ACM":         1,
		"CONTEST_MODE_IOI":         2,
		"CONTEST_MODE_OI":          3,
		"CONTEST_MODE_CODEFORCES":  4,
		"CONTEST_MODE_ATCODER":     5,
	}
)

func (x ContestMode) Enum() *ContestMode {
	p := new(ContestMode)
	*p = x
	return p
}

func (x ContestMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContestMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rin_contest_v1_contest_proto_enumTypes[0].Descriptor()
}

func (ContestMode) Type() protoreflect.EnumType {
	return &file_rin_contest_v1_contest_proto_enumTypes[0]
}

func (x ContestMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContestMode.Descriptor instead.
func (ContestMode) EnumDescriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{0}
}

type CreateContestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Mode          ContestMode            `protobuf:"varint,3,opt,name=mode,proto3,enum=rin.contest.v1.ContestMode" json:"mode,omitempty"`
	StartsAtUnix  int64                  `protobuf:"varint,4,opt,name=starts_at_unix,json=startsAtUnix,proto3" json:"starts_at_unix,omitempty"`
	EndsAtUnix    int64                  `protobuf:"varint,5,opt,name=ends_at_unix,json=endsAtUnix,proto3" json:"ends_at_unix,omitempty"`
	ProblemIds    []string               `protobuf:"bytes,6,rep,name=problem_ids,json=problemIds,proto3" json:"problem_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContestRequest) Reset() {
	*x = CreateContestRequest{}
	mi := &file_rin_contest_v1_contest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContestRequest) ProtoMessage() {}

func (x *CreateContestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_contest_v1_contest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContestRequest.ProtoReflect.Descriptor instead.
func (*CreateContestRequest) Descriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContestRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CreateContestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateContestRequest) GetMode() ContestMode {
	if x != nil {
		return x.Mode
	}
	return ContestMode_CONTEST_MODE_UNSPECIFIED
}

func (x *CreateContestRequest) GetStartsAtUnix() int64 {
	if x != nil {
		return x.StartsAtUnix
	}
	return 0
}

func (x *CreateContestRequest) GetEndsAtUnix() int64 {
	if x != nil {
		return x.EndsAtUnix
	}
	return 0
}

func (x *CreateContestRequest) GetProblemIds() []string {
	if x != nil {
		return x.ProblemIds
	}
	return nil
}

type Contest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContestId        string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Mode             ContestMode            `protobuf:"varint,3,opt,name=mode,proto3,enum=rin.contest.v1.ContestMode" json:"mode,omitempty"`
	StartsAtUnix     int64                  `protobuf:"varint,4,opt,name=starts_at_unix,json=startsAtUnix,proto3" json:"starts_at_unix,omitempty"`
	EndsAtUnix       int64                  `protobuf:"varint,5,opt,name=ends_at_unix,json=endsAtUnix,proto3" json:"ends_at_unix,omitempty"`
	ScoreboardFrozen bool                   `protobuf:"varint,6,opt,name=scoreboard_frozen,json=scoreboardFrozen,proto3" json:"scoreboard_frozen,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Contest) Reset() {
	*x = Contest{}
	mi := &file_rin_contest_v1_contest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contest) ProtoMessage() {}

func (x *Contest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_contest_v1_contest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contest.ProtoReflect.Descriptor instead.
func (*Contest) Descriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{1}
}

func (x *Contest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *Contest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Contest) GetMode() ContestMode {
	if x != nil {
		return x.Mode
	}
	return ContestMode_CONTEST_MODE_UNSPECIFIED
}

func (x *Contest) GetStartsAtUnix() int64 {
	if x != nil {
		return x.StartsAtUnix
	}
	return 0
}

func (x *Contest) GetEndsAtUnix() int64 {
	if x != nil {
		return x.EndsAtUnix
	}
	return 0
}

func (x *Contest) GetScoreboardFrozen() bool {
	if x != nil {
		return x.ScoreboardFrozen
	}
	return false
}

type RegisterContestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ContestId     string                 `protobuf:"bytes,2,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	InviteCode    string                 `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterContestRequest) Reset() {
	*x = RegisterContestRequest{}
	mi := &file_rin_contest_v1_contest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterContestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterContestRequest) ProtoMessage() {}

func (x *RegisterContestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_contest_v1_contest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterContestRequest.ProtoReflect.Descriptor instead.
func (*RegisterContestRequest) Descriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterContestRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RegisterContestRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *RegisterContestRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type ContestRegistration struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContestId        string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	ActorId          string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TeamId           string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RegisteredAtUnix int64                  `protobuf:"varint,4,opt,name=registered_at_unix,json=registeredAtUnix,proto3" json:"registered_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContestRegistration) Reset() {
	*x = ContestRegistration{}
	mi := &file_rin_contest_v1_contest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestRegistration) ProtoMessage() {}

func (x *ContestRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_rin_contest_v1_contest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestRegistration.ProtoReflect.Descriptor instead.
func (*ContestRegistration) Descriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{3}
}

func (x *ContestRegistration) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *ContestRegistration) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ContestRegistration) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ContestRegistration) GetRegisteredAtUnix() int64 {
	if x != nil {
		return x.RegisteredAtUnix
	}
	return 0
}

type GetScoreboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreboardRequest) Reset() {
	*x = GetScoreboardRequest{}
	mi := &file_rin_contest_v1_contest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreboardRequest) ProtoMessage() {}

func (x *GetScoreboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_contest_v1_contest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreboardRequest.ProtoReflect.Descriptor instead.
func (*GetScoreboardRequest) Descriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{4}
}

func (x *GetScoreboardRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *GetScoreboardRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetScoreboardRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Scoreboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Rows          []*ScoreboardRow       `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scoreboard) Reset() {
	*x = Scoreboard{}
	mi := &file_rin_contest_v1_contest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scoreboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scoreboard) ProtoMessage() {}

func (x *Scoreboard) ProtoReflect() protoreflect.Message {
	mi := &file_rin_contest_v1_contest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scoreboard.ProtoReflect.Descriptor instead.
func (*Scoreboard) Descriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{5}
}

func (x *Scoreboard) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *Scoreboard) GetRows() []*ScoreboardRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *Scoreboard) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type ScoreboardRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Rank          int64                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Penalty       int64                  `protobuf:"varint,5,opt,name=penalty,proto3" json:"penalty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreboardRow) Reset() {
	*x = ScoreboardRow{}
	mi := &file_rin_contest_v1_contest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreboardRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreboardRow) ProtoMessage() {}

func (x *ScoreboardRow) ProtoReflect() protoreflect.Message {
	mi := &file_rin_contest_v1_contest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreboardRow.ProtoReflect.Descriptor instead.
func (*ScoreboardRow) Descriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreboardRow) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ScoreboardRow) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ScoreboardRow) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ScoreboardRow) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreboardRow) GetPenalty() int64 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

type StreamScoreboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamScoreboardRequest) Reset() {
	*x = StreamScoreboardRequest{}
	mi := &file_rin_contest_v1_contest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamScoreboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamScoreboardRequest) ProtoMessage() {}

func (x *StreamScoreboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_contest_v1_contest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamScoreboardRequest.ProtoReflect.Descriptor instead.
func (*StreamScoreboardRequest) Descriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{7}
}

func (x *StreamScoreboardRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

type ScoreboardEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ChangedRows   []*ScoreboardRow       `protobuf:"bytes,3,rep,name=changed_rows,json=changedRows,proto3" json:"changed_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreboardEvent) Reset() {
	*x = ScoreboardEvent{}
	mi := &file_rin_contest_v1_contest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreboardEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreboardEvent) ProtoMessage() {}

func (x *ScoreboardEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rin_contest_v1_contest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreboardEvent.ProtoReflect.Descriptor instead.
func (*ScoreboardEvent) Descriptor() ([]byte, []int) {
	return file_rin_contest_v1_contest_proto_rawDescGZIP(), []int{8}
}

func (x *ScoreboardEvent) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *ScoreboardEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ScoreboardEvent) GetChangedRows() []*ScoreboardRow {
	if x != nil {
		return x.ChangedRows
	}
	return nil
}

var File_rin_contest_v1_contest_proto protoreflect.FileDescriptor

const file_rin_contest_v1_contest_proto_rawDesc = "" +
	"\n" +
	"\x1crin/contest/v1/contest.proto\x12\x0erin.contest.v1\"\xe1\x01\n" +
	"\x14CreateContestRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12/\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1b.rin.contest.v1.ContestModeR\x04mode\x12$\n" +
	"\x0estarts_at_unix\x18\x04 \x01(\x03R\fstartsAtUnix\x12 \n" +
	"\fends_at_unix\x18\x05 \x01(\x03R\n" +
	"endsAtUnix\x12\x1f\n" +
	"\vproblem_ids\x18\x06 \x03(\tR\n" +
	"problemIds\"\xe4\x01\n" +
	"\aContest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12/\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1b.rin.contest.v1.ContestModeR\x04mode\x12$\n" +
	"\x0estarts_at_unix\x18\x04 \x01(\x03R\fstartsAtUnix\x12 \n" +
	"\fends_at_unix\x18\x05 \x01(\x03R\n" +
	"endsAtUnix\x12+\n" +
	"\x11scoreboard_frozen\x18\x06 \x01(\bR\x10scoreboardFrozen\"s\n" +
	"\x16RegisterContestRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x02 \x01(\tR\tcontestId\x12\x1f\n" +
	"\vinvite_code\x18\x03 \x01(\tR\n" +
	"inviteCode\"\x96\x01\n" +
	"\x13ContestRegistration\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12,\n" +
	"\x12registered_at_unix\x18\x04 \x01(\x03R\x10registeredAtUnix\"j\n" +
	"\x14GetScoreboardRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x7f\n" +
	"\n" +
	"Scoreboard\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x121\n" +
	"\x04rows\x18\x02 \x03(\v2\x1d.rin.contest.v1.ScoreboardRowR\x04rows\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\"\x91\x01\n" +
	"\rScoreboardRow\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x03R\x04rank\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\x12\x18\n" +
	"\apenalty\x18\x05 \x01(\x03R\apenalty\"8\n" +
	"\x17StreamScoreboardRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\"\x8a\x01\n" +
	"\x0fScoreboardEvent\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12@\n" +
	"\fchanged_rows\x18\x03 \x03(\v2\x1d.rin.contest.v1.ScoreboardRowR\vchangedRows*\xa3\x01\n" +
	"\vContestMode\x12\x1c\n" +
	"\x18CONTEST_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CONTEST_MODE_ACM\x10\x01\x12\x14\n" +
	"\x10CONTEST_MODE_IOI\x10\x02\x12\x13\n" +
	"\x0fCONTEST_MODE_OI\x10\x03\x12\x1b\n" +
	"\x17CONTEST_MODE_CODEFORCES\x10\x04\x12\x18\n" +
	"\x14CONTEST_MODE_ATCODER\x10\x052\xf3\x02\n" +
	"\x0eContestService\x12N\n" +
	"\rCreateContest\x12$.rin.contest.v1.CreateContestRequest\x1a\x17.rin.contest.v1.Contest\x12^\n" +
	"\x0fRegisterContest\x12&.rin.contest.v1.RegisterContestRequest\x1a#.rin.contest.v1.ContestRegistration\x12Q\n" +
	"\rGetScoreboard\x12$.rin.contest.v1.GetScoreboardRequest\x1a\x1a.rin.contest.v1.Scoreboard\x12^\n" +
	"\x10StreamScoreboard\x12'.rin.contest.v1.StreamScoreboardRequest\x1a\x1f.rin.contest.v1.ScoreboardEvent0\x01BCZAgithub.com/rin-oj/rin-oj/packages/sdk-go/rin/contest/v1;contestv1b\x06proto3"

var (
	file_rin_contest_v1_contest_proto_rawDescOnce sync.Once
	file_rin_contest_v1_contest_proto_rawDescData []byte
)

func file_rin_contest_v1_contest_proto_rawDescGZIP() []byte {
	file_rin_contest_v1_contest_proto_rawDescOnce.Do(func() {
		file_rin_contest_v1_contest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rin_contest_v1_contest_proto_rawDesc), len(file_rin_contest_v1_contest_proto_rawDesc)))
	})
	return file_rin_contest_v1_contest_proto_rawDescData
}

var file_rin_contest_v1_contest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rin_contest_v1_contest_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rin_contest_v1_contest_proto_goTypes = []any{
	(ContestMode)(0),                // 0: rin.contest.v1.ContestMode
	(*CreateContestRequest)(nil),    // 1: rin.contest.v1.CreateContestRequest
	(*Contest)(nil),                 // 2: rin.contest.v1.Contest
	(*RegisterContestRequest)(nil),  // 3: rin.contest.v1.RegisterContestRequest
	(*ContestRegistration)(nil),     // 4: rin.contest.v1.ContestRegistration
	(*GetScoreboardRequest)(nil),    // 5: rin.contest.v1.GetScoreboardRequest
	(*Scoreboard)(nil),              // 6: rin.contest.v1.Scoreboard
	(*ScoreboardRow)(nil),           // 7: rin.contest.v1.ScoreboardRow
	(*StreamScoreboardRequest)(nil), // 8: rin.contest.v1.StreamScoreboardRequest
	(*ScoreboardEvent)(nil),         // 9: rin.contest.v1.ScoreboardEvent
}
var file_rin_contest_v1_contest_proto_depIdxs = []int32{
	0, // 0: rin.contest.v1.CreateContestRequest.mode:type_name -> rin.contest.v1.ContestMode
	0, // 1: rin.contest.v1.Contest.mode:type_name -> rin.contest.v1.ContestMode
	7, // 2: rin.contest.v1.Scoreboard.rows:type_name -> rin.contest.v1.ScoreboardRow
	7, // 3: rin.contest.v1.ScoreboardEvent.changed_rows:type_name -> rin.contest.v1.ScoreboardRow
	1, // 4: rin.contest.v1.ContestService.CreateContest:input_type -> rin.contest.v1.CreateContestRequest
	3, // 5: rin.contest.v1.ContestService.RegisterContest:input_type -> rin.contest.v1.RegisterContestRequest
	5, // 6: rin.contest.v1.ContestService.GetScoreboard:input_type -> rin.contest.v1.GetScoreboardRequest
	8, // 7: rin.contest.v1.ContestService.StreamScoreboard:input_type -> rin.contest.v1.StreamScoreboardRequest
	2, // 8: rin.contest.v1.ContestService.CreateContest:output_type -> rin.contest.v1.Contest
	4, // 9: rin.contest.v1.ContestService.RegisterContest:output_type -> rin.contest.v1.ContestRegistration
	6, // 10: rin.contest.v1.ContestService.GetScoreboard:output_type -> rin.contest.v1.Scoreboard
	9, // 11: rin.contest.v1.ContestService.StreamScoreboard:output_type -> rin.contest.v1.ScoreboardEvent
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rin_contest_v1_contest_proto_init() }
func file_rin_contest_v1_contest_proto_init() {
	if File_rin_contest_v1_contest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rin_contest_v1_contest_proto_rawDesc), len(file_rin_contest_v1_contest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rin_contest_v1_contest_proto_goTypes,
		DependencyIndexes: file_rin_contest_v1_contest_proto_depIdxs,
		EnumInfos:         file_rin_contest_v1_contest_proto_enumTypes,
		MessageInfos:      file_rin_contest_v1_contest_proto_msgTypes,
	}.Build()
	File_rin_contest_v1_contest_proto = out.File
	file_rin_contest_v1_contest_proto_goTypes = nil
	file_rin_contest_v1_contest_proto_depIdxs = nil
}
