// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: rin/judge/v1/judge.proto

package judgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JudgeDispatcherService_Submit_FullMethodName      = "/rin.judge.v1.JudgeDispatcherService/Submit"
	JudgeDispatcherService_Languages_FullMethodName   = "/rin.judge.v1.JudgeDispatcherService/Languages"
	JudgeDispatcherService_HealthCheck_FullMethodName = "/rin.judge.v1.JudgeDispatcherService/HealthCheck"
)

// JudgeDispatcherServiceClient is the client API for JudgeDispatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JudgeDispatcherServiceClient interface {
	Submit(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JudgeResult], error)
	Languages(ctx context.Context, in *ListJudgeLanguagesRequest, opts ...grpc.CallOption) (*ListJudgeLanguagesResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type judgeDispatcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgeDispatcherServiceClient(cc grpc.ClientConnInterface) JudgeDispatcherServiceClient {
	return &judgeDispatcherServiceClient{cc}
}

func (c *judgeDispatcherServiceClient) Submit(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JudgeResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JudgeDispatcherService_ServiceDesc.Streams[0], JudgeDispatcherService_Submit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JudgeRequest, JudgeResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JudgeDispatcherService_SubmitClient = grpc.ServerStreamingClient[JudgeResult]

func (c *judgeDispatcherServiceClient) Languages(ctx context.Context, in *ListJudgeLanguagesRequest, opts ...grpc.CallOption) (*ListJudgeLanguagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJudgeLanguagesResponse)
	err := c.cc.Invoke(ctx, JudgeDispatcherService_Languages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeDispatcherServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, JudgeDispatcherService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeDispatcherServiceServer is the server API for JudgeDispatcherService service.
// All implementations must embed UnimplementedJudgeDispatcherServiceServer
// for forward compatibility.
type JudgeDispatcherServiceServer interface {
	Submit(*JudgeRequest, grpc.ServerStreamingServer[JudgeResult]) error
	Languages(context.Context, *ListJudgeLanguagesRequest) (*ListJudgeLanguagesResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedJudgeDispatcherServiceServer()
}

// UnimplementedJudgeDispatcherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJudgeDispatcherServiceServer struct{}

func (UnimplementedJudgeDispatcherServiceServer) Submit(*JudgeRequest, grpc.ServerStreamingServer[JudgeResult]) error {
	return status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedJudgeDispatcherServiceServer) Languages(context.Context, *ListJudgeLanguagesRequest) (*ListJudgeLanguagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Languages not implemented")
}
func (UnimplementedJudgeDispatcherServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedJudgeDispatcherServiceServer) mustEmbedUnimplementedJudgeDispatcherServiceServer() {
}
func (UnimplementedJudgeDispatcherServiceServer) testEmbeddedByValue() {}

// UnsafeJudgeDispatcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JudgeDispatcherServiceServer will
// result in compilation errors.
type UnsafeJudgeDispatcherServiceServer interface {
	mustEmbedUnimplementedJudgeDispatcherServiceServer()
}

func RegisterJudgeDispatcherServiceServer(s grpc.ServiceRegistrar, srv JudgeDispatcherServiceServer) {
	// If the following call pancis, it indicates UnimplementedJudgeDispatcherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JudgeDispatcherService_ServiceDesc, srv)
}

func _JudgeDispatcherService_Submit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JudgeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JudgeDispatcherServiceServer).Submit(m, &grpc.GenericServerStream[JudgeRequest, JudgeResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JudgeDispatcherService_SubmitServer = grpc.ServerStreamingServer[JudgeResult]

func _JudgeDispatcherService_Languages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJudgeLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeDispatcherServiceServer).Languages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeDispatcherService_Languages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeDispatcherServiceServer).Languages(ctx, req.(*ListJudgeLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeDispatcherService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeDispatcherServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeDispatcherService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeDispatcherServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JudgeDispatcherService_ServiceDesc is the grpc.ServiceDesc for JudgeDispatcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JudgeDispatcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rin.judge.v1.JudgeDispatcherService",
	HandlerType: (*JudgeDispatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Languages",
			Handler:    _JudgeDispatcherService_Languages_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _JudgeDispatcherService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Submit",
			Handler:       _JudgeDispatcherService_Submit_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rin/judge/v1/judge.proto",
}
