// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rin/judge/v1/judge.proto

package judgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JudgeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId    string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	ProblemId       string                 `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	LanguageId      string                 `protobuf:"bytes,3,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	SourceObjectKey string                 `protobuf:"bytes,4,opt,name=source_object_key,json=sourceObjectKey,proto3" json:"source_object_key,omitempty"`
	TestCases       []*TestCase            `protobuf:"bytes,5,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	Limit           *ResourceLimit         `protobuf:"bytes,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JudgeRequest) Reset() {
	*x = JudgeRequest{}
	mi := &file_rin_judge_v1_judge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeRequest) ProtoMessage() {}

func (x *JudgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_judge_v1_judge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeRequest.ProtoReflect.Descriptor instead.
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return file_rin_judge_v1_judge_proto_rawDescGZIP(), []int{0}
}

func (x *JudgeRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *JudgeRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *JudgeRequest) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *JudgeRequest) GetSourceObjectKey() string {
	if x != nil {
		return x.SourceObjectKey
	}
	return ""
}

func (x *JudgeRequest) GetTestCases() []*TestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

func (x *JudgeRequest) GetLimit() *ResourceLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type TestCase struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TestCaseId      string                 `protobuf:"bytes,1,opt,name=test_case_id,json=testCaseId,proto3" json:"test_case_id,omitempty"`
	InputObjectKey  string                 `protobuf:"bytes,2,opt,name=input_object_key,json=inputObjectKey,proto3" json:"input_object_key,omitempty"`
	OutputObjectKey string                 `protobuf:"bytes,3,opt,name=output_object_key,json=outputObjectKey,proto3" json:"output_object_key,omitempty"`
	SubtaskIndex    int32                  `protobuf:"varint,4,opt,name=subtask_index,json=subtaskIndex,proto3" json:"subtask_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_rin_judge_v1_judge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_rin_judge_v1_judge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_rin_judge_v1_judge_proto_rawDescGZIP(), []int{1}
}

func (x *TestCase) GetTestCaseId() string {
	if x != nil {
		return x.TestCaseId
	}
	return ""
}

func (x *TestCase) GetInputObjectKey() string {
	if x != nil {
		return x.InputObjectKey
	}
	return ""
}

func (x *TestCase) GetOutputObjectKey() string {
	if x != nil {
		return x.OutputObjectKey
	}
	return ""
}

func (x *TestCase) GetSubtaskIndex() int32 {
	if x != nil {
		return x.SubtaskIndex
	}
	return 0
}

type ResourceLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuTimeMs     int64                  `protobuf:"varint,1,opt,name=cpu_time_ms,json=cpuTimeMs,proto3" json:"cpu_time_ms,omitempty"`
	WallTimeMs    int64                  `protobuf:"varint,2,opt,name=wall_time_ms,json=wallTimeMs,proto3" json:"wall_time_ms,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	StackBytes    int64                  `protobuf:"varint,4,opt,name=stack_bytes,json=stackBytes,proto3" json:"stack_bytes,omitempty"`
	OutputBytes   int64                  `protobuf:"varint,5,opt,name=output_bytes,json=outputBytes,proto3" json:"output_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimit) Reset() {
	*x = ResourceLimit{}
	mi := &file_rin_judge_v1_judge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimit) ProtoMessage() {}

func (x *ResourceLimit) ProtoReflect() protoreflect.Message {
	mi := &file_rin_judge_v1_judge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimit.ProtoReflect.Descriptor instead.
func (*ResourceLimit) Descriptor() ([]byte, []int) {
	return file_rin_judge_v1_judge_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceLimit) GetCpuTimeMs() int64 {
	if x != nil {
		return x.CpuTimeMs
	}
	return 0
}

func (x *ResourceLimit) GetWallTimeMs() int64 {
	if x != nil {
		return x.WallTimeMs
	}
	return 0
}

func (x *ResourceLimit) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimit) GetStackBytes() int64 {
	if x != nil {
		return x.StackBytes
	}
	return 0
}

func (x *ResourceLimit) GetOutputBytes() int64 {
	if x != nil {
		return x.OutputBytes
	}
	return 0
}

type JudgeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	TestCaseId    string                 `protobuf:"bytes,2,opt,name=test_case_id,json=testCaseId,proto3" json:"test_case_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TimeMs        int64                  `protobuf:"varint,4,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Final         bool                   `protobuf:"varint,7,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeResult) Reset() {
	*x = JudgeResult{}
	mi := &file_rin_judge_v1_judge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResult) ProtoMessage() {}

func (x *JudgeResult) ProtoReflect() protoreflect.Message {
	mi := &file_rin_judge_v1_judge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResult.ProtoReflect.Descriptor instead.
func (*JudgeResult) Descriptor() ([]byte, []int) {
	return file_rin_judge_v1_judge_proto_rawDescGZIP(), []int{3}
}

func (x *JudgeResult) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *JudgeResult) GetTestCaseId() string {
	if x != nil {
		return x.TestCaseId
	}
	return ""
}

func (x *JudgeResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JudgeResult) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *JudgeResult) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *JudgeResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JudgeResult) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type ListJudgeLanguagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJudgeLanguagesRequest) Reset() {
	*x = ListJudgeLanguagesRequest{}
	mi := &file_rin_judge_v1_judge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJudgeLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJudgeLanguagesRequest) ProtoMessage() {}

func (x *ListJudgeLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_judge_v1_judge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJudgeLanguagesRequest.ProtoReflect.Descriptor instead.
func (*ListJudgeLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_rin_judge_v1_judge_proto_rawDescGZIP(), []int{4}
}

type JudgeLanguage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LanguageId    string                 `protobuf:"bytes,1,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	CompileFlags  []string               `protobuf:"bytes,4,rep,name=compile_flags,json=compileFlags,proto3" json:"compile_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeLanguage) Reset() {
	*x = JudgeLanguage{}
	mi := &file_rin_judge_v1_judge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeLanguage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeLanguage) ProtoMessage() {}

func (x *JudgeLanguage) ProtoReflect() protoreflect.Message {
	mi := &file_rin_judge_v1_judge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeLanguage.ProtoReflect.Descriptor instead.
func (*JudgeLanguage) Descriptor() ([]byte, []int) {
	return file_rin_judge_v1_judge_proto_rawDescGZIP(), []int{5}
}

func (x *JudgeLanguage) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *JudgeLanguage) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *JudgeLanguage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *JudgeLanguage) GetCompileFlags() []string {
	if x != nil {
		return x.CompileFlags
	}
	return nil
}

type ListJudgeLanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []*JudgeLanguage       `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJudgeLanguagesResponse) Reset() {
	*x = ListJudgeLanguagesResponse{}
	mi := &file_rin_judge_v1_judge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJudgeLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJudgeLanguagesResponse) ProtoMessage() {}

func (x *ListJudgeLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rin_judge_v1_judge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJudgeLanguagesResponse.ProtoReflect.Descriptor instead.
func (*ListJudgeLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_rin_judge_v1_judge_proto_rawDescGZIP(), []int{6}
}

func (x *ListJudgeLanguagesResponse) GetLanguages() []*JudgeLanguage {
	if x != nil {
		return x.Languages
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_rin_judge_v1_judge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rin_judge_v1_judge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_rin_judge_v1_judge_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_rin_judge_v1_judge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rin_judge_v1_judge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_rin_judge_v1_judge_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_rin_judge_v1_judge_proto protoreflect.FileDescriptor

const file_rin_judge_v1_judge_proto_rawDesc = "" +
	"\n" +
	"\x18rin/judge/v1/judge.proto\x12\frin.judge.v1\"\x89\x02\n" +
	"\fJudgeRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\tR\tproblemId\x12\x1f\n" +
	"\vlanguage_id\x18\x03 \x01(\tR\n" +
	"languageId\x12*\n" +
	"\x11source_object_key\x18\x04 \x01(\tR\x0fsourceObjectKey\x125\n" +
	"\n" +
	"test_cases\x18\x05 \x03(\v2\x16.rin.judge.v1.TestCaseR\ttestCases\x121\n" +
	"\x05limit\x18\x06 \x01(\v2\x1b.rin.judge.v1.ResourceLimitR\x05limit\"\xa7\x01\n" +
	"\bTestCase\x12 \n" +
	"\ftest_case_id\x18\x01 \x01(\tR\n" +
	"testCaseId\x12(\n" +
	"\x10input_object_key\x18\x02 \x01(\tR\x0einputObjectKey\x12*\n" +
	"\x11output_object_key\x18\x03 \x01(\tR\x0foutputObjectKey\x12#\n" +
	"\rsubtask_index\x18\x04 \x01(\x05R\fsubtaskIndex\"\xb8\x01\n" +
	"\rResourceLimit\x12\x1e\n" +
	"\vcpu_time_ms\x18\x01 \x01(\x03R\tcpuTimeMs\x12 \n" +
	"\fwall_time_ms\x18\x02 \x01(\x03R\n" +
	"wallTimeMs\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\x12\x1f\n" +
	"\vstack_bytes\x18\x04 \x01(\x03R\n" +
	"stackBytes\x12!\n" +
	"\foutput_bytes\x18\x05 \x01(\x03R\voutputBytes\"\xd8\x01\n" +
	"\vJudgeResult\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12 \n" +
	"\ftest_case_id\x18\x02 \x01(\tR\n" +
	"testCaseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\atime_ms\x18\x04 \x01(\x03R\x06timeMs\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x14\n" +
	"\x05final\x18\a \x01(\bR\x05final\"\x1b\n" +
	"\x19ListJudgeLanguagesRequest\"\x92\x01\n" +
	"\rJudgeLanguage\x12\x1f\n" +
	"\vlanguage_id\x18\x01 \x01(\tR\n" +
	"languageId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12#\n" +
	"\rcompile_flags\x18\x04 \x03(\tR\fcompileFlags\"W\n" +
	"\x1aListJudgeLanguagesResponse\x129\n" +
	"\tlanguages\x18\x01 \x03(\v2\x1b.rin.judge.v1.JudgeLanguageR\tlanguages\"\x14\n" +
	"\x12HealthCheckRequest\"e\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\x8f\x02\n" +
	"\x16JudgeDispatcherService\x12A\n" +
	"\x06Submit\x12\x1a.rin.judge.v1.JudgeRequest\x1a\x19.rin.judge.v1.JudgeResult0\x01\x12^\n" +
	"\tLanguages\x12'.rin.judge.v1.ListJudgeLanguagesRequest\x1a(.rin.judge.v1.ListJudgeLanguagesResponse\x12R\n" +
	"\vHealthCheck\x12 .rin.judge.v1.HealthCheckRequest\x1a!.rin.judge.v1.HealthCheckResponseB?Z=github.com/rin-oj/rin-oj/packages/sdk-go/rin/judge/v1;judgev1b\x06proto3"

var (
	file_rin_judge_v1_judge_proto_rawDescOnce sync.Once
	file_rin_judge_v1_judge_proto_rawDescData []byte
)

func file_rin_judge_v1_judge_proto_rawDescGZIP() []byte {
	file_rin_judge_v1_judge_proto_rawDescOnce.Do(func() {
		file_rin_judge_v1_judge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rin_judge_v1_judge_proto_rawDesc), len(file_rin_judge_v1_judge_proto_rawDesc)))
	})
	return file_rin_judge_v1_judge_proto_rawDescData
}

var file_rin_judge_v1_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rin_judge_v1_judge_proto_goTypes = []any{
	(*JudgeRequest)(nil),               // 0: rin.judge.v1.JudgeRequest
	(*TestCase)(nil),                   // 1: rin.judge.v1.TestCase
	(*ResourceLimit)(nil),              // 2: rin.judge.v1.ResourceLimit
	(*JudgeResult)(nil),                // 3: rin.judge.v1.JudgeResult
	(*ListJudgeLanguagesRequest)(nil),  // 4: rin.judge.v1.ListJudgeLanguagesRequest
	(*JudgeLanguage)(nil),              // 5: rin.judge.v1.JudgeLanguage
	(*ListJudgeLanguagesResponse)(nil), // 6: rin.judge.v1.ListJudgeLanguagesResponse
	(*HealthCheckRequest)(nil),         // 7: rin.judge.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 8: rin.judge.v1.HealthCheckResponse
}
var file_rin_judge_v1_judge_proto_depIdxs = []int32{
	1, // 0: rin.judge.v1.JudgeRequest.test_cases:type_name -> rin.judge.v1.TestCase
	2, // 1: rin.judge.v1.JudgeRequest.limit:type_name -> rin.judge.v1.ResourceLimit
	5, // 2: rin.judge.v1.ListJudgeLanguagesResponse.languages:type_name -> rin.judge.v1.JudgeLanguage
	0, // 3: rin.judge.v1.JudgeDispatcherService.Submit:input_type -> rin.judge.v1.JudgeRequest
	4, // 4: rin.judge.v1.JudgeDispatcherService.Languages:input_type -> rin.judge.v1.ListJudgeLanguagesRequest
	7, // 5: rin.judge.v1.JudgeDispatcherService.HealthCheck:input_type -> rin.judge.v1.HealthCheckRequest
	3, // 6: rin.judge.v1.JudgeDispatcherService.Submit:output_type -> rin.judge.v1.JudgeResult
	6, // 7: rin.judge.v1.JudgeDispatcherService.Languages:output_type -> rin.judge.v1.ListJudgeLanguagesResponse
	8, // 8: rin.judge.v1.JudgeDispatcherService.HealthCheck:output_type -> rin.judge.v1.HealthCheckResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rin_judge_v1_judge_proto_init() }
func file_rin_judge_v1_judge_proto_init() {
	if File_rin_judge_v1_judge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rin_judge_v1_judge_proto_rawDesc), len(file_rin_judge_v1_judge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rin_judge_v1_judge_proto_goTypes,
		DependencyIndexes: file_rin_judge_v1_judge_proto_depIdxs,
		MessageInfos:      file_rin_judge_v1_judge_proto_msgTypes,
	}.Build()
	File_rin_judge_v1_judge_proto = out.File
	file_rin_judge_v1_judge_proto_goTypes = nil
	file_rin_judge_v1_judge_proto_depIdxs = nil
}
